### ISSUE TITLE
MSTR additional 29,646 BTC - $650 million purchase

### ISSUE THREAD

**Issue by alonshvartsman** [nvk/bitcointreasuries.org#100]
https://www.microstrategy.com/en/company/company-videos/microstrategy-announces-over-1b-in-total-bitcoin-purchases-in-2020

**Comment by nvk** [comment]
https://twitter.com/michael_saylor/status/1341006691408752640

**Comment by nvk** [comment]
live https://twitter.com/BTCtreasuries/status/1341028742307737600?s=20
