### ISSUE TITLE
Microstrategy Percentage wrong

### ISSUE THREAD

**Issue by ViktorBohu** [nvk/bitcointreasuries.org#101]
70,470 BTC / 18,577,468 BTC = 0.379% not 0.194%

**Comment by nvk** [comment]
We go 21m here.

**Comment by ViktorBohu** [comment]
That's still 0.3368%

70,740 / 21,000,000 = 0.00336857

**Comment by nvk** [comment]
You are totally right, the formula broken when I expanded the list. It's fixed now.

Thanks
