### ISSUE TITLE
New: Mogo

### ISSUE THREAD

**Issue by tristanhcole** [nvk/bitcointreasuries.org#104]
- [ ] Name: Mogo
- [ ] Exchange: TSX:MOGO
- [ ] https://www.businesswire.com/news/home/20201223005205/en/Mogo-to-Make-Corporate-Investment-in-Bitcoin/
- [ ] Basis price: $XXX USD
- [ ] Market Cap: $XXX USD
- [ ] Total BTC: XXX BTC
- [ ] Direct link to latest financial report

**Comment by nvk** [comment]
not enough detail or amount
