### ISSUE TITLE
COINSILIUM 

### ISSUE THREAD

**Issue by tboydsto** [nvk/bitcointreasuries.org#105]
- [x] Name: COINSILIUM
- [x] Exchange: AQSE:COIN, OTCQB:CINGF
- [X] Link to google finance or wherever I can find it: https://www.google.com/finance/quote/CINGF:OTCMKTS
- [ ] Basis price: $XXX USD
- [ ] Market Cap: $XXX USD
- [ ] Total BTC: XXX BTC
- [x] Direct link to latest financial report:  https://www.coinsilium.com/investors/nex-exchange-rule-71

**Comment by tboydsto** [comment]
Quote from article:

_London, UK, 21 December 2020 - Coinsilium Group Limited (AQSE:COIN) (OTCQB:CINGF) the Blockchain, Open Finance and Crypto Finance venture operator, is pleased to provide an update regarding its cryptocurrency treasury position and staking activities.
 
**As at 21 December 2020, the USD value of Coinsilium's fully vested cryptocurrency and token treasury, excluding cash at bank, stood at USD1,090,674. This is predominantly denominated in highly liquid cryptocurrencies and tokens including BTC, ETH, ICX and RIF**. In addition to Coinsilium's current cryptocurrency and token treasury position, there is also a further USD127,190.67 at current value, of RIF tokens which will vest monthly over the forthcoming 23 months._

**Comment by tboydsto** [comment]
I scoured the financials, but could not find details on actual BTC holdings

**Comment by nvk** [comment]
thanks.

not enough public detail or enough money/btc to qualify.
