### ISSUE TITLE
New: Mass Mutual private company $100 Million purchase of Bitcoin

### ISSUE THREAD

**Issue by optionsforcashdotcom** [nvk/bitcointreasuries.org#107]
- [ ] Name: Mass Mutual
- [ ] Exchange: PRIVATE
- [ ] Link to google : https://www.coindesk.com/massmutual-buys-100m-bitcoin-bets-on-institutional-adoption-with-5m-nydig-stake
- [ ] Basis price: $100,000,000 USD
- [ ] Market Cap: $XXX USD
- [ ] Total BTC: XXX BTC
- [ ] Direct link to latest financial report

**Comment by nvk** [comment]
See closed issues, no official details.
