### ISSUE TITLE
Galaxy Digital: Updated BTC holdings

### ISSUE THREAD

**Issue by freemarkit** [nvk/bitcointreasuries.org#108]
<img width="710" alt="Screen Shot 2020-12-26 at 9 30 48 AM" src="https://user-images.githubusercontent.com/21041574/103156420-40d28080-475d-11eb-8ba5-ce021d6315b8.png">

16,402 BTC as of 9/30/20
https://assets.ctfassets.net/rbgwch8v5pod/1PTGMG7W9Y0HzEm7YGDgY6/d639acbaf23e60e9d10d35da520ea316/GDH_LP_MD_A_Q3_20_FINAL.pdf

**Comment by nvk** [comment]
they sold some eh.

**Comment by nvk** [comment]
updated https://twitter.com/BTCtreasuries/status/1346999696666013699?s=20
