### ISSUE TITLE
definition of treasuries?

### ISSUE THREAD

**Issue by bgrobbins** [nvk/bitcointreasuries.org#109]
Looking into the Voyager treasury.  Voyager doesn't really own any digital assets.  They are just holding them on behalf of their customers.  If you see note 3 in the link, they have crypto listed as both an asset (held for clients) and a liability that they owe to clients.  I think the company itself only has a very small amount of digital assets, $269k.

**Comment by nvk** [comment]
![Uploading 103174114...]
