### ISSUE TITLE
Hut-8 on Toronto Stock Exchange (TSX)

### ISSUE THREAD

**Issue by SovereignNode** [nvk/bitcointreasuries.org#11]
HI. Hut 8 is a Canadian mining company with BTC on Balance sheet.

BTC mainly acquired through mining - so no purchase price available.

Latest report: https://hut8mining.com/wp-content/uploads/2020/08/Hut-8-FS-Q2-2020-Final.pdf

As of June 2020 (see page 14)
Balance, June 30, 202036,788,573$    2,954

Can we include the portion they use as collateral for their loan?

**Comment by nvk** [comment]
Neat, but it's not on the filing how much BTC they have.

**Comment by SovereignNode** [comment]
![2020-10-09 (3)](https://user-images.githubusercontent.com/49792942/95600493-c50c4600-0a41-11eb-8c0c-13941786ad74.png)

See Note 5

**Comment by nvk** [comment]
So the BTC is on the balance sheet, but not controlled by this company. Maybe could still qualify I guess.

**Comment by SovereignNode** [comment]
Yeah as long as they pay off the interest, I would opt to include it. If they get liquidated, balance should be changed accordingly.

**Comment by efecini** [comment]
I think it is applicable too.

**Comment by nvk** [comment]
added
