### ISSUE TITLE
Bitcoingroup SE 

### ISSUE THREAD

**Issue by comenda** [nvk/bitcointreasuries.org#110]
- [ ] Name: Bitcoingroup SE 
- [ ] Exchange: symbol (XETRA:ADE) or https://bitcoingroup.com/en/stock/basic-data
- [ ] Link to google finance or wherever I can find it https://www.investing.com/equities/bitcoin-group-se
- [ ] Basis price: $XXX USD
- [ ] Market Cap: 345.5M EUR
- [ ] Total BTC: They don't give the breakdown but they hold 33.8 M in Crypto as per Fin Statements (mid 2020)
- [ ] Direct link to latest financial report https://bitcoingroup.com/images/PDF/FB_2020/BitcoinGroup_HJB2020_EN.pdf (page 36)

There is another group but haven't checked them yet - Called 21Shares which is ETF listed on main EU markets 
- https://www.investing.com/etfs/amun-bitcoin-crypto-single-tracker?cid=1166890
- https://www.investing.com/etfs/amun-bitcoin-crypto-single-tracker

**Comment by comenda** [comment]
They are the owners of https://www.bitcoin.de/en?cr=1

**Comment by nvk** [comment]
no breakdown.
