### ISSUE TITLE
New CI Galaxy Bitcoin Fund ETF

### ISSUE THREAD

**Issue by nickg902** [nvk/bitcointreasuries.org#114]
Name: CI Galaxy Bitcoin Fund
Exchange: TSX:BTCG.U
Link: https://money.tmx.com/en/quote/BTCG.U
Basis price: $9.70 USD
Market Cap: $600,950,001 USD
Total BTC: 15750 BTC
Direct Link: https://www.newswire.ca/news-releases/ci-galaxy-bitcoin-fund-begins-trading-on-the-toronto-stock-exchange-galaxy-digital-appointed-sub-advisor-870104524.html

**Comment by nickg902** [comment]
updated and removed template

**Comment by nvk** [comment]
updated https://twitter.com/BTCtreasuries/status/1346999696666013699?s=20
