### ISSUE TITLE
Neptune Digital Assets Corp.

### ISSUE THREAD

**Issue by MarketMadness90** [nvk/bitcointreasuries.org#115]
- [ ] Name: Neptune Digital Assets Corp TSXV
- [ ] Exchange: symbol (TSXV: DASH, OTC; NPPTF, FSE: 1NW) 
- [ ] https://www.bloomberg.com/quote/DASH:CN
- [ ] Basis price: $0.28 CAD
- [ ] Market Cap: $24,523,000 CAD
- [ ] Total BTC: 75 BTC
- [ ] https://www.neptunedash.com/financials/2020-31-Aug-FS.pdf

**Please review existing <a href="https://github.com/nvk/bitcointreasuries.org/issues?q=is%3Aissue+is%3Aclosed">closed</a> and open issues before creating a new submission, don't submit just an article without any other information.**

**Comment by nvk** [comment]
updated https://twitter.com/BTCtreasuries/status/1346999696666013699?s=20
