### ISSUE TITLE
NexTech has now $4M in BTC

### ISSUE THREAD

**Issue by alelorca** [nvk/bitcointreasuries.org#117]
- [x] Name: NexTech AR
- [x] Exchange: (OTCQB: NEXCF) (CSE: NTAR) (FSE: N29)
- [x] Link to google finance or wherever I can find it: https://finance.yahoo.com/quote/NEXCF
- [x] Basis price: $4M USD
- [x] Market Cap: $400M USD
- [x] Total BTC: 130.178 BTC
- [x] Direct link to latest financial report: https://www.nextechar.com/press-releases-and-media/nextech-increases-its-treasury-bitcoin-holdings-to-4million

**Comment by nvk** [comment]
updated https://twitter.com/BTCtreasuries/status/1346999696666013699?s=20
