### ISSUE TITLE
Fortress Blockchain

### ISSUE THREAD

**Issue by 0xfff** [nvk/bitcointreasuries.org#118]
- [x] Name: Fortress Blockchain
- [x] Exchange: TSXV:FORT
- [x] Link to google finance or wherever I can find it https://money.tmx.com/en/quote/FORT
- [x] Basis price: $77.1 BTC on October 27, 2020 at a price of CDN$18,026 (approximately US$13,550).  USD
39.6 Bitcoin which were acquired in the first week of May 2020
- [x] Market Cap: $16.4MCAD = 13.12 USD
- [x] Total BTC: 163.2 BTC
- [x] Direct link to latest financial report: https://money.tmx.com/en/quote/FORT/news/5663488473346998/Fortress_Technologies_Inc_Announces_Third_Quarter_2020_Financial_Results

**Please review existing <a href="https://github.com/nvk/bitcointreasuries.org/issues?q=is%3Aissue+is%3Aclosed">closed</a> and open issues before creating a new submission, don't submit just an article without any other information.**

**Comment by nvk** [comment]
updated https://twitter.com/BTCtreasuries/status/1346999696666013699?s=20
