### ISSUE TITLE
Argo Blockchain missing OTCMKTS ticker.

### ISSUE THREAD

**Issue by pilvlp** [nvk/bitcointreasuries.org#119]
- [ ] Name: Argo Blockchain PLC
- [ ] Exchange: OTCPK:ARBKF
- [ ] https://polaris.brighterir.com/public/argo_blockchain/news/rns/story/rnp6pjx
- [ ] Basis price: $1.5 USD
- [ ] Market Cap: $377M USD
- [ ] Total BTC: 209 BTC
- [ ] Direct link to latest financial report: https://polaris.brighterir.com/public/argo_blockchain/news/rns/story/xppgljx

**Comment by nvk** [comment]
Does any tracker list this company? Google Finance? Bloomberg? etc?

**Comment by pilvlp** [comment]
https://research.tdameritrade.com/grid/public/research/stocks/summary?symbol=ARBKF
https://finance.yahoo.com/quote/ARBKF
https://www.bloomberg.com/quote/ARBKF:US
https://www.google.com/finance/quote/ARBKF:OTCMKTS

**Comment by pilvlp** [comment]
From the London stock exchange regarding their addition to the OTCPK market:
https://www.londonstockexchange.com/news-article/ARB/application-to-the-otcqb-venture-market-in-the-us/14807697

**Comment by nvk** [comment]
So, is this just an addition of coin to Argo LSE:ARB or is this a new entity with another 209 BTC?

**Comment by pilvlp** [comment]
It's the same company being listed on a US market. Their plan is to move from OTCPK to OTCQB for additional exposure.

Per the article I shared: 

Peter Wall, Chief Executive of Argo Blockchain, said: "We want to make Argo available to US markets in order to gain access to a broader investor base and enhance our visibility in North America. We are already trading on OTCPK and we anticipate a full OTC listing with wider investor reach in the coming days."

**Comment by nvk** [comment]
updated https://twitter.com/BTCtreasuries/status/1347012486969626632?s=20

**Comment by pilvlp** [comment]
Sorry, I believe both tickers should be listed, to be fair. The company operates under both.

ARB for UK(https://www.google.com/finance/quote/ARB:LON)
ARBKF for US(https://www.google.com/finance/quote/ARBKF:OTCMKTS)

If you look at the above links - the market cap is the same for both tickers.
