### ISSUE TITLE
Argo Blockchain (LSE:ARB)

### ISSUE THREAD

**Issue by arkoni84** [nvk/bitcointreasuries.org#12]
LSE publically traded company
7th October operational update for September 2020
126 BTC in treasury

**Comment by nvk** [comment]
Got a link to public filings?

**Comment by arkoni84** [comment]
https://www.londonstockexchange.com/news-article/ARB/september-operational-update-loi-signing/14711686

**Comment by nvk** [comment]
Added, do you know what their basis price was?

**Comment by arkoni84** [comment]
Should be $1.34m!

Great work with this by the way!
