### ISSUE TITLE
Update BIGG Digital Assets Inc (CSE: BIGG)

### ISSUE THREAD

**Issue by markgukov** [nvk/bitcointreasuries.org#120]
- [ ] Name: BIGG Digital Assets Inc.
- [ ] Exchange: symbol (CSE:BIGG)
- [ ] Link to google finance - https://www.google.ca/search?q=CNSX:+BIGG
- [ ] Bitcoin Purchase Basis price: $1,909,259 USD
- [ ] Market Cap: $7,485,942 USD
- [ ] Total BTC: 189.5 BTC
- [ ] Direct link to latest financial report - https://www.globenewswire.com/news-release/2020/12/08/2141282/0/en/BIGG-Digital-Assets-Inc-Purchases-Additional-40-Bitcoins-for-Treasury-Total-Bitcoin-Treasury-Reaches-189-5-BTC.html

Related to #44. Thanks.

**Comment by nvk** [comment]
live https://twitter.com/BTCtreasuries/status/1347296865004498944?s=20
