### ISSUE TITLE
Update Hut 8 BTC holdings for Q3 2020

### ISSUE THREAD

**Issue by operahouserat** [nvk/bitcointreasuries.org#121]
Hut 8 bitcoin holdings as of 9/30/2020 were 2,851 BTC, according to their Q3 2020 filing here (pg. 14):

https://sedar.com/GetFile.do?lang=EN&docClass=5&issuerNo=00033355&issuerType=03&projectNo=03134222&docId=4831594

**Comment by nvk** [comment]
live https://twitter.com/BTCtreasuries/status/1347296865004498944?s=20
