### ISSUE TITLE
BIGG double entry

### ISSUE THREAD

**Issue by markgukov** [nvk/bitcointreasuries.org#122]
Thanks for adding this quickly. However, there are two entries now:

<img width="1007" alt="Screen Shot 2021-01-07 at 4 42 18 PM" src="https://user-images.githubusercontent.com/201282/103960667-84d36700-5107-11eb-83eb-82773119fb6e.png">

Could you please consolidate the two, fixing the market cap link?

Thanks

**Comment by nvk** [comment]
thx! consolidated on the ticker that works with GF.
