### ISSUE TITLE
Adding Bitfarms Limited (BITF or BFARF)

### ISSUE THREAD

**Issue by UltimateJatt** [nvk/bitcointreasuries.org#123]
1. Ticker:  BITF  (TSXV) / BFARF (PINX)
2. https://bitfarms.com/app/uploads/2020/11/BITFARMS-Q3-2020-FS-FINAL.pdf
3. 2437 BTC as of September 30, 2020
4. 2437 coins = $ 21,421,000 USD (~$8790 USD per coin) [September 30, 2020]

**Comment by nvk** [comment]
Please follow the template, thanks!
