### ISSUE TITLE
Add Bitfarms Limited

### ISSUE THREAD

**Issue by UltimateJatt** [nvk/bitcointreasuries.org#124]
- [ ] Name: Bitfarms Limited
- [ ] Exchange: CVE: BITF  or OTCMKTS: BFARF
- [ ] https://www.google.ca/search?q=bitf&tbm=fin#scso=__6v4X6zpKoG0tAbXgqfQCg7:0
- [ ] Bitcoin Purchase Basis price: $8790 USD
- [ ] Market Cap: $246,000,000 USD
- [ ] Total BTC: 2437 BTC
- [ ] https://bitfarms.com/app/uploads/2020/11/BITFARMS-Q3-2020-FS-FINAL.pdf

**Please review existing <a href="https://github.com/nvk/bitcointreasuries.org/issues?q=is%3Aissue+is%3Aclosed">closed</a> and open issues before creating a new submission, don't submit just an article without any other information.**

**Comment by nvk** [comment]
dup #125

**Comment by UltimateJatt** [comment]
That is a very good catch.  I called their Investor relations  and the President confirmed that they sell all the bitcoin they mine.  They are now in the early phase of actually keeping bitcoin on hand.
