### ISSUE TITLE
Bitfarms Limited

### ISSUE THREAD

**Issue by UltimateJatt** [nvk/bitcointreasuries.org#125]
- [ ] Name: Bitfarms Limited
- [ ] Exchange: CSE: BITF 
- [ ] https://www.google.ca/search?q=bitf&tbm=fin#scso=_G8r4X9DYBMKztAaAvIT4CQ7:0
- [ ] Bitcoin Purchase Basis price: $8790 USD
- [ ] Market Cap: $179,610,000 USD
- [ ] Total BTC: 2437 BTC
- [ ] https://bitfarms.com/app/uploads/2020/11/BITFARMS-Q3-2020-FS-FINAL.pdf

**Please review existing <a href="https://github.com/nvk/bitcointreasuries.org/issues?q=is%3Aissue+is%3Aclosed">closed</a> and open issues before creating a new submission, don't submit just an article without any other information.**

**Comment by BankinBTC21** [comment]
This is an incorrect reading of the financial statement. 2437 BTC is the total BTC mined during the 9 month period, not the amount of BTC they hold on their balance sheet. This report doesn't make it clear how much BTC they presently hold, but it can't be even close to that much:

(in 000's)
![image](https://user-images.githubusercontent.com/77289773/104210346-9f4b6000-53e7-11eb-8713-fffb8503dd11.png)

**Comment by nvk** [comment]
Good catch. Will remove them till it's cleared.
