### ISSUE TITLE
Bitcoin Group SE

### ISSUE THREAD

**Issue by onedaysg1983** [nvk/bitcointreasuries.org#128]
- [ ] Name: Bitcoin Group SE
- [ ] Exchange: ADE:GR
- [ ] Link to google finance or wherever I can find it: https://www.bloomberg.com/quote/ADE:GR
- [ ] Bitcoin Purchase Basis price: $XXX USD
- [ ] Market Cap: $369.81m USD (EUR 302.5m according to BBG converted in USD)
- [ ] Total BTC: >122.25m USD equivalent (>100m EUR mentioned in the press-release
- [ ] Direct link to latest financial report: https://bitcoingroup.com/en/corporatenews/2020/bitcoin-group-se-own-stock-of-cryptocurrencies-breaks-the-eur-100-million-barrier

**Please review existing <a href="https://github.com/nvk/bitcointreasuries.org/issues?q=is%3Aissue+is%3Aclosed">closed</a> and open issues before creating a new submission, don't submit just an article without any other information.**

**Comment by nvk** [comment]
live https://twitter.com/BTCtreasuries/status/1349377521113038848?s=20
