### ISSUE TITLE
A few Bitcoin companies

### ISSUE THREAD

**Issue by derickca** [nvk/bitcointreasuries.org#132]
I don’t know if all of these companies qualify to be on Bitcoin Treasuries, but I’m sure some of them do:
•	PayPal, PYPL
•	Overstock, OSTK
•	Marathon Patent Group, MARA
•	8i Enterprises Acquisition, JFK
•	Ubi Blockchain Internet, UBIA
•	Bitfarms, BITF.V
•	BTCS Inc., BTCS
•	DMG Blockchain, DMGGF
•	Blockchain Industries, BCII
•	Blockchainfound, BCFN.CN
•	Blockchain Foundry, BLFDF
•	Long Blockchain Corp., LBCC
•	Graph Blockchain, REGRF
•	iMining Blockchain & Cryptocurrency, IBKKF
•	Web Blockchain Media, WEBB

**Comment by nvk** [comment]
Please follow the template for each, only submit if all items are available

**Comment by derickca** [comment]
No thanks. Without these companies the site is inaccurate.
