### ISSUE TITLE
Remove Nextech AR

### ISSUE THREAD

**Issue by alelorca** [nvk/bitcointreasuries.org#133]
They sold all the treasuries.

https://www.nextechar.com/press-releases-and-media/nextech-sells-its-treasury-bitcoin-holding-sand-books-a-profit

**Comment by mjamin** [comment]
> The news that has emerged is that a critical flaw called a ‘double spend’ may have occurred, which if true allows someone to spend the same Bitcoin twice undermining faith in the system.
😂

**Comment by nvk** [comment]
will do later... what a moron.

**Comment by nvk** [comment]
removed
