### ISSUE TITLE
MARATHON INVESTS $150 MILLION IN BITCOIN

### ISSUE THREAD

**Issue by Ntanistas** [nvk/bitcointreasuries.org#135]
https://www.marathonpg.com/news/press-releases/detail/1224/marathon-invests-150-million-in-bitcoin

**Comment by Ntanistas** [comment]
LAS VEGAS, Jan. 25, 2021 (GLOBE NEWSWIRE) -- Marathon Patent Group, Inc. (NASDAQ:MARA) ("Marathon" or "Company"), one of the largest enterprise Bitcoin self-mining companies in North America, today announced that it has purchased 4,812.66 BTC in an aggregate purchase price of $150 million. As a result, the Company has strengthened its position as one of the only Nasdaq-listed, pure-play investment options for individuals and institutions seeking exposure to Bitcoin.

**Comment by earonesty** [comment]
why closed?

**Comment by nvk** [comment]
dup, please don't re-open issues.
