### ISSUE TITLE
New: Marathon Patent Group

### ISSUE THREAD

**Issue by obsidience** [nvk/bitcointreasuries.org#136]
- [x] Name: Marathon Patent Group
- [x] Exchange: NASDAQ:MARA
- [x] https://www.google.com/finance/quote/MARA:NASDAQ
- [x] $31167.79 USD
- [x] $1.72B USD
- [x] 4812.66 BTC
- [x] https://www.nasdaq.com/market-activity/stocks/mara/financials

https://www.marathonpg.com/news/press-releases/detail/1224/marathon-invests-150-million-in-bitcoin
(copy) https://www.globenewswire.com/Search?runSearchId=46839926
https://www.coindesk.com/miner-marathon-buys-bitcoin-investment

**Comment by Ntanistas** [comment]
Nice job!

**Comment by nvk** [comment]
Awesome, that's for doing my homework. I will add it today :)

**Comment by nvk** [comment]
live https://twitter.com/BTCtreasuries/status/1353710351041368064?s=20
