### ISSUE TITLE
Updated: Advanced Bitcoin Technologies now listed at Yahoo Finance

### ISSUE THREAD

**Issue by airbone42** [nvk/bitcointreasuries.org#137]
The already listed Advanced Bitcoin Technologies AG (ABT:GR) is now also listed including its market cap at Yahoo Finance: https://finance.yahoo.com/quote/ABT.DU?p=ABT.DU&.tsrc=fin-srch

Therefore, could you please updated the markep cap accordingly? Thanks in advance!

Best,
Tobias.

**Comment by nvk** [comment]
For live market cap we need Google Finance listing
