### ISSUE TITLE
3iq the bitcoin fund - Update

### ISSUE THREAD

**Issue by marcodiomede** [nvk/bitcointreasuries.org#138]
Name: 3iQ The Bitcoin Fund
Exchange: TSX:QBTC.U
Link: https://money.tmx.com/en/quote/QBTC.U
IPO price: $10.00 USD
NAV at Inception: $9.2396 USD
Market Cap: $757,861,738.06 USD
Total BTC: 22,589.81 BTC
% BTC: 100%
Direct link to latest financial report: https://3iq.ca/the-bitcoin-fund/ and sedar.com
Latest fund holdings available at: https://docs.google.com/spreadsheets/d/1rnO1Q1ijb-qSdBAFeyXzX4fYfxJLfdyz308LXo776no/edit?usp=sharing
Data as of january 25, 2020.

**Comment by nvk** [comment]
thx, live https://twitter.com/BTCtreasuries/status/1354087443797073920?s=20
