### ISSUE TITLE
Update - ETC Group Bitcoin ETP

### ISSUE THREAD

**Issue by marcodiomede** [nvk/bitcointreasuries.org#139]
https://btc-etc.com/products/btcetc.html
As of 26/01/2021 they have 0.00098707 BTC/share x 13,008,894 shares =12840 BTC.
Don't look to "Total Holdings (AUM in Bitcoin)", since it is calculated as  Values of AUM (USD)/Bitcoin Price (USD)  but BTC price is not updated.

**Comment by nvk** [comment]
thx, live https://twitter.com/BTCtreasuries/status/1354087443797073920?s=20
