### ISSUE TITLE
CI / Galaxy Fund AUM is overstated by 547%

### ISSUE THREAD

**Issue by freemarkit** [nvk/bitcointreasuries.org#140]
The actual AUM from the CI/Galaxy website is $109,351,924.41 USD. Here's their website:
https://www.firstasset.com/solutions/overview/?fund=CI+Galaxy+Bitcoin+Fund

The TMX data is incorrect
https://money.tmx.com/en/quote/BTCG.U

- [ ] Name: Coin Citadel OTC
- [ ] Exchange: symbol (NASDA:SQ) or wherever I can find it
- [ ] Link to google finance or wherever I can find it
- [ ] Bitcoin Purchase Basis price: $XXX USD
- [ ] Market Cap: $XXX USD
- [ ] Total BTC: XXX BTC
- [ ] Direct link to latest financial report

**Please review existing <a href="https://github.com/nvk/bitcointreasuries.org/issues?q=is%3Aissue+is%3Aclosed">closed</a> and open issues before creating a new submission, don't submit just an article without any other information.**

**Comment by nvk** [comment]
Whats your estimated BTC count for them?

**Comment by freemarkit** [comment]
Using CI/Galaxy's reporting website, multiply the BTC Per Unit of 0.00045 times the Units Outstanding of 7,347,381. That equals 3,306 of BTC in their treasury. 

At yesterday's close of approximately $33,200 BTC price, that's the $109 million of AUM they are reporting. 

https://www.firstasset.com/solutions/overview/?fund=CI+Galaxy+Bitcoin+Fund

**Comment by marcodiomede** [comment]
Your calculations are correct, but there is something strange with CI/Galaxy's reporting website. Yesterday i visited it looking for updates and they reported the same data that are visible now but the note (1) indicated that these data were as of december 2021 (don't remember the day displayed).
Anyway we have to trust data as they are reported, so 3306

**Comment by nvk** [comment]
That's similar calculation, I'm finding odd that TSX data is wrong.

**Comment by freemarkit** [comment]
I sent an email to my contact at TMX to notice them of the issue. Data integrity is super important.

------
[NAME],

The TMX website is updated appropriately and we now have access to the investor kit. Thanks for all your help!

There is a data issue on one of our competitor's TMX pages, CI / Galaxy Fund (TSX: BTCG.U). The market cap is incorrectly listed as $542m while the fund managers reporting website shows $109m. The error is with the units outstanding. It’s quoted on TMX as 35k but only should be 7.3k. 

LMK if you can help clear that up. Thanks again!

**Comment by nvk** [comment]
updated

**Comment by freemarkit** [comment]
TSX just fixed the error of overstating market cap via the share count. All good!
https://money.tmx.com/en/quote/BTCG.U
