### ISSUE TITLE
Cypherpunk Holdings (HODL) Updated Filings

### ISSUE THREAD

**Issue by nachoguru** [nvk/bitcointreasuries.org#141]
I actually hodl HODL so I hate to be the guy to drop their ranking, but bitcointreasuries.org can only remain a valuable resource if we all do our best to help keep it updated. 

Since HODL is listed on the Canadian Securities Exchange, it has to file monthly updates. These are available to the public at https://www.thecse.com/en/listings/diversified-industries/cypherpunk-holdings-inc where you can click **CSE Filings** near bottom right for a pop-up listing.

On Jan 7th they filed *Monthly Progress Report - December 2020* which states under item 1:

> At the end of December the Company owns 231.9 Bitcoin 

...and under item 7:

> During December 2020 the Company sold 44.6 bitcoin and invested Euros 100,000 ($ 158,763) in a convertible note which includes the right to participate in NGRAVE’s Series A financing round for an additional undisclosed amount.

Then, on Jan 11th, they issued a press release, *Cypherpunk Holdings Inc. Announces Receipt of Dividend from Wasabi Wallet* that you can see on their website at https://cypherpunkholdings.com/press/ or the direct PDF download link: https://cypherpunkholdings.com/wp-content/uploads/2021/01/announces_receipt_of_dividend_from_wasabi_wallet_-jan_11_2020_final-.pdf 

The TL;DR of that one is:

>  pleased to announce the receipt of a dividend for the fiscal year 2020 from its portfolio company zkSnacks Limited

and 

> The dividend was paid entirely in Bitcoin, totalling 2.7 BTC with a recorded value of $106,110 USD. The sum was received on January 11th, 2021.

...so now they have 234.6 Bitcoin by my math, at least as far as we the public know so far.

As a shareholder, I would love to see them regain their ranking soon by hodling over 300 BTC. So I hope the company will release another update soon, indicating they've bought Bitcoin with the C$2,980,120 proceeds of their recent private placement announced Jan 15th: https://cypherpunkholdings.com/wp-content/uploads/2021/01/2021-01-15_cypherpunk_holdings_inc_announces_closing_of_oversubscribed_non-brokered_private_placement_final.pdf 

Thanks for creating the site, @nvk !

**Comment by nvk** [comment]
Ooof, sell BTC to invest in a closed source HW...

Will update soon

**Comment by nvk** [comment]
updated
