### ISSUE TITLE
BTCS.Inc, how to classify? (Today SEC filling, 76k BTC)

### ISSUE THREAD

**Issue by marcodiomede** [nvk/bitcointreasuries.org#142]
- Name of enterprise: BTCS.Inc
- Exchange symbol:  (BTCS)
- https://finance.yahoo.com/quote/BTCS?p=BTCS&.tsrc=fin-srch
- Bitcoin Purchase Basis price: ?
- Market Cap: ?
- Total BTC: 78.534 BTC
- https://www.sec.gov/Archives/edgar/data/1436229/000149315221001796/form10-k.htm

This doesn't seem to be a proper Fund. It resembles more a service of BTC custody for customers, but given the size i felt obliged to report here.  By the way, it is not BTCS core business - they acquired another business, the "Digital Asset Initiative".

In the SEC filing it is stated (page 20) that "In the event that the Digital Assets held by us exceed 40% of our total assets, exclusive of cash, we may inadvertently become an investment company. In order to limit our acquisition of Digital Securities to stay within the 40% threshold (...)" So it isn't an ETF like fund. 
Ad we don't know who are the investors that have used BTCS to buy BTC: they may be companies already listed in the treasuries page as "public traded".

So, in my opinion it should be listed separatedly in the website, or not listed at all. But we're talking about 78K BTC, so i reported here. Just in case...

![SEC](https://user-images.githubusercontent.com/31670120/105909730-40612a00-6028-11eb-84a0-e4ad64e63de2.png)

**Comment by nvk** [comment]
The ownership is really what maters, as I understand In their case they don't own it or have it in trust (AUM), so they don't really count as an single entity HODLing it.

**Comment by marcodiomede** [comment]
Ok, thank you very much for the clarification. And thank you for creating the site @nvk !
