### ISSUE TITLE
Bit Digital, Inc.

### ISSUE THREAD

**Issue by 521314** [nvk/bitcointreasuries.org#144]
Name:Bit Digital, Inc.
NASDAQ:BTBT

Announcement link : https://bit-digital.com/press-releases
Official website : https://www.bit-digital.com/

1510.19 btc on December 18,2020
(Financial report reference : https://www.sec.gov/Archives/edgar/data/1710350/000121390020043684/ea131995ex99-1_bitdigital.htm)

As of the filing date on December 18,2020, We have earned an aggregation of 1331.2 bitcoins and recognized unaudited revenues of approximately $16.50 million. The averaged purchase price is $16.50 Million / 1331.2 = $12,394.

Market Capitalization : $938.776M

**Comment by nvk** [comment]
So you increased your hodl from 189.5 to 1331.2?

**Comment by nvk** [comment]
Please confirm this:

![image](https://user-images.githubusercontent.com/797193/106325693-39fdc880-6249-11eb-9136-75770b09ddbf.png)

**Comment by nvk** [comment]
Seems like 239.3 is the new total

**Comment by nvk** [comment]
all sorted out and updated https://twitter.com/BTCtreasuries/status/1355263131820417024?s=20
