### ISSUE TITLE
Cypherpunk Holdings (HODL) Updated Filings as of Jan 29 2021

### ISSUE THREAD

**Issue by nachoguru** [nvk/bitcointreasuries.org#145]
Hey @nvk looks like the world is watching, your site got a shout out in the latest HODL press release! (also: Called it!)

See https://cypherpunkholdings.com/press/ or direct PDF link https://cypherpunkholdings.com/wp-content/uploads/2021/01/2021-01-29-cypherpunk-holdings-inc-announces-updated-bitcoin-holdings.pdf  or excerpt below:

> Toronto, Ontario--(Newsfile Corp. - January 29, 2021) - Cypherpunk Holdings Inc. (CSE: HODL) ("Cypherpunk" or the "Company") a sector leader for privacy-technology investments is pleased to announce that it has increased its total Bitcoin (BTC) holdings to BTC 291.64. This represents a net increase since September 30, 2020 of 27.9 BTC.

> The increase in Bitcoin holdings is a partial use of proceeds from a private placement of $2,980,120 CAD that closed on January 15th, 2021.

> During October 2020, Cypherpunk Holdings Inc. was added to the unofficial list of public companies with a treasury position in Bitcoin alongside other companies such as MicroStrategy, Square, and Galaxy Digital Holdings. The website for Bitcoin Treasuries can be found at https://bitcointreasuries.org/

**Comment by nvk** [comment]
Neat!

**Comment by nachoguru** [comment]
Hi @nvk I see the site hasn't changed yet, so I fear I may have buried the lead above -- please see in the quote above, HODL's numbers actually changed to 291.64 Bitcoin.

I see you are still showing 235 on the site so I thought I'd ping you here.
