### ISSUE TITLE
New: Ninepoint Bitcoin Trust

### ISSUE THREAD

**Issue by obsidience** [nvk/bitcointreasuries.org#146]
- [x] Name: (Toronto) Ninepoint Partners LP "Bitcoin Trust"
- [x] Exchange: TSX:BITC.U
- [x] https://www.ninepoint.com/funds/bitcoin-trust/
- [x] Bitcoin Purchase Basis price: ~$30,888.84 USD
- [x] Market Cap: $183,506,744.07 USD
- [x] Total BTC: 
- Total Units (7,318,276 Class A Units, 2,865,314 Class F Units and 7,806,901 Class S Units) * BTC per Unit (0.000304468)
- = ~5477.528813788BTC (appreciate it if someone can check my math but it looks close to the market cap)
- [x] Links:
https://www.ninepoint.com/funds/bitcoin-trust/
https://www.ninepoint.com/media/618390/ninepoint-bitcoin-trust-prospectus.pdf
https://www.ninepoint.com/about-ninepoint/press-releases/bitcoin-trust-fully-invested-on-first-day-of-trading/
https://cointelegraph.com/news/following-in-grayscale-s-footsteps-new-bitcoin-trust-goes-public-in-canada

**Comment by nvk** [comment]
thx! live https://twitter.com/BTCtreasuries/status/1356611497217175559
