### ISSUE TITLE
Mode Global Holdings

### ISSUE THREAD

**Issue by jimboelf123** [nvk/bitcointreasuries.org#149]
- [ ] Name: Mode Global Holdings
- [ ] Exchange: symbol: MODE.L
- [ ] https://www.investegate.co.uk/mode-global-holdings--mode-/rns/mode-adopts-bitcoin-as-treasury-reserve-asset/202010210700037078C/
- [ ] Bitcoin Purchase Basis price: $11,485.67 USD
- [ ] Market Cap: £36,644,337 GBP
- [ ] Total BTC: 84.8962 BTC
- [ ] https://ir.q4europe.com/solutions/ModePlc/4070/newsArticle.aspx?storyid=14837092

**Please review existing <a href="https://github.com/nvk/bitcointreasuries.org/issues?q=is%3Aissue+is%3Aclosed">closed</a> and open issues before creating a new submission, don't submit just an article without any other information.**

**Comment by nvk** [comment]
live https://twitter.com/BTCtreasuries/status/1356611497217175559
