### ISSUE TITLE
Ruffer liquidation of cost basis

### ISSUE THREAD

**Issue by tboydsto** [nvk/bitcointreasuries.org#150]
source

https://coinmarketcap.com/headlines/news/ruffer-bitcoin-profits/

In December 2020, Ruffer Investment revealed that their overall exposure to Bitcoin was around 2.7% of their assets under management, roughly equivalent to 45,000 BTC. Ruffer primarily made this investment to hedge their risks against "some of the risks that we see in a fragile monetary system and distorted financial markets." 

Recently, MacInnes revealed:

“The 2.5pc allocation we made in November across all our funds, which totaled around $600m. This has more than doubled so we decided to take out our ‘book cost’ and take $650m in profits. We still have around $700m left in and are currently up by $750m overall.”

I cannot find details on Ruffer

**Comment by nvk** [comment]
That's the problem with their numbers, no good source.
