### ISSUE TITLE
Riot Blockchain, Inc. Update

### ISSUE THREAD

**Issue by matthewkreh** [nvk/bitcointreasuries.org#151]
On the page https://ir.riotblockchain.com/all-sec-filings

The 10-Q from 11/09/20 shows:

"For the quarterly period ended September 30, 2020"

"Cryptocurrencies 8,987" (in thousands)

**Comment by nvk** [comment]
How much BTC in the books, don't care about shitcoins. Would be great if these companies made the numbers clear like MSTR

**Comment by nachoguru** [comment]
On it... reaching out to IR to ask them to issue a clarifying PR.
