### ISSUE TITLE
Possible missed info in #145

### ISSUE THREAD

**Issue by nachoguru** [nvk/bitcointreasuries.org#152]
Hi @nvk pls see my comment on #145 as I was also sharing their new BTC balance in the quote there.

Or if that's not valid because it's not on a quarterly filing or something, please let me know. 

Although the downwards update I submitted previously was also not on a quarterly report yet so I don't think that's it... I think I just distracted you from the updated figures with my first sentence there. :)

Thanks!

**Comment by nvk** [comment]
dup #154 (now with ann)
