### ISSUE TITLE
Grayscale 616K => 649K BTC not live

### ISSUE THREAD

**Issue by ViktorBohu** [nvk/bitcointreasuries.org#153]
This update is not live on the website:

https://twitter.com/BTCtreasuries/status/1356611497217175559

![image](https://user-images.githubusercontent.com/18405140/106827844-76865580-6689-11eb-9de2-f11ac1bbdb66.jpeg)

**Comment by ViktorBohu** [comment]
See #148

**Comment by nvk** [comment]
updated

**Comment by ViktorBohu** [comment]
Still not live

![image](https://user-images.githubusercontent.com/18405140/106915705-9e67ce80-6706-11eb-8862-61e86de7d9e5.png)

**Comment by nvk** [comment]
prob cached, it's live for me.
