### ISSUE TITLE
Tesla

### ISSUE THREAD

**Issue by W944** [nvk/bitcointreasuries.org#157]
https://www.sec.gov/ix?doc=/Archives/edgar/data/1318605/000156459021004599/tsla-10k_20201231.htm

**Comment by ErikBjare** [comment]
Beat me to it by seconds!

**Comment by W944** [comment]
I'm reading the SEC doc and unless I'm scanning wrong it doesn't say how many actual coins they have other then the fiat 1.5 BN$ value

**Comment by marcodiomede** [comment]
They didn't say HOW they bought it. Maybe they have bought using Grayscale, so they are already in our data

**Comment by W944** [comment]
Indeed, looks like we'll need a bit more time for more info to come out.

**Comment by nvk** [comment]
Could you guys get us the exact basis price, I will be in the computer in a few and could update asap with all the info in hand.

**Comment by DavidPinilla1** [comment]
> I'm reading the SEC doc and unless I'm scanning wrong it doesn't say how many actual coins they have other then the fiat 1.5 BN$ value

At page 23, first paragraph fourth line says:
`Thereafter, we invested an aggregate $1.50 billion in bitcoin under this policy and may acquire and hold digital assets from time to time or long-term`

**Comment by djpnewton** [comment]
Could put in an estimate of the BTC with an asterisk?

**Comment by nvk** [comment]
No point in listing with public details, that's the whole purpose of this site :)

**Comment by LukeParker** [comment]
If Michael Saylor is right in his recent Bloomberg interview, we're about to be flooded with thousands of companies and other institutions that we'll only learn about through their SEC filing, just like Tesla. They won't have a reason to disclose how many coins or their basis price, but their combined wealth will be far, far larger than the rest of the entries on bitcointreasuries. :(

**Comment by DavidPinilla1** [comment]
> Could put in an estimate of the BTC with an asterisk?

It is a good idea. However, I would put Unknown and some red/yellow color letting know people that we only know the $ amount.

**Comment by isaacito** [comment]
wen TSLA?

**Comment by nvk** [comment]
Wen they have details.

**Comment by nvk** [comment]
added https://twitter.com/BTCtreasuries/status/1362800822359371788?s=20
