### ISSUE TITLE
Elon Musk (TSLA) buys bitcoin - see filings 10k

### ISSUE THREAD

**Issue by FT-77** [nvk/bitcointreasuries.org#158]
https://www.sec.gov/ix?doc=/Archives/edgar/data/1318605/000156459021004599/tsla-10k_20201231.htm

$1.5 billion confirmed buy. Price was not stated in filings but I'm sure further news will follow. They bought January 2021 so assuming their average price is around $32-35k. Just posting this to put on your radar for when they do disclose their price.

**Comment by nvk** [comment]
dup #157
