### ISSUE TITLE
Bitfarms Limited

### ISSUE THREAD

**Issue by UltimateJatt** [nvk/bitcointreasuries.org#159]
- [ ] Name: Bitfarms Limited
- [ ] Exchange: CSE: BITF  OTC: BFARF
- [ ] https://www.google.ca/search?q=bitf&tbm=fin#scso=_G8r4X9DYBMKztAaAvIT4CQ7:0,_Xz0hYKe2FpDctQa4hInACQ7:0
- [ ] Bitcoin Purchase Basis price: $7500 USD
- [ ] Market Cap: $325,000,000 USD
- [ ] Total BTC: 150 BTC
- [ ] https://www.businesswire.com/news/home/20210204005407/en/Bitfarms-Provides-Corporate-Update-on-Growth-and-Activity
- [ ] https://bitfarms.com/investors/

**Comment by nvk** [comment]
live
