### ISSUE TITLE
CoinShares XBT Provider Certificates

### ISSUE THREAD

**Issue by meltdem** [nvk/bitcointreasuries.org#16]
Bitcoin Tracker One (Bloomberg: COINXBT:SS) and Bitcoin Tracker Euro (Bloomberg: COINXBE:SS) are both publicly listed on the Nasdaq in Stockholm and throughout trading venues and brokers in Europe. 

Certificates are created and redeemed on a daily basis, since these are ETPs, and bitcoin balances backing the ETP can be found at https://real-time-attest.trustexplorer.io/coinshares - as of today, it's $771M in bitcoin.

**Comment by nvk** [comment]
1. Is [SEK:COINXBT:SS] correct or is this a OTCQX like GBTC?
2. Whats the actual number of BTC?

**Comment by meltdem** [comment]
There are 2 products – an SEK product and a EUR product. They are not like GBTC. Shares are created and redeemed daily and there is no premium because when someone buys a share, we buy the underlying amount of bitcoin and likewise, when someone sells a share, we sell the underlying amount of bitcoin. It’s a true ETF so the NAV fluctuates throughout the trading day – we usually trade $4 – 8M a day.

The actual number of BTC is holdings / price. So $770,170,932 / $11,045 = 69,730 BTC as of market close on Friday

When markets in Europe on Tuesday, this could change, but updating the # of BTC monthly should be more than adequate because the numbers don’t change that much, just the price of BTC does!

**Comment by nvk** [comment]
Ok, added with value based on Oct 9th report.
