### ISSUE TITLE
21Shares updated BTC holdings 

### ISSUE THREAD

**Issue by EliezerNdinga** [nvk/bitcointreasuries.org#161]
- [ ] Name: 21Shares
- [ ] Total BTC: 6,945.10465 BTC

**Please review existing <a href="https://github.com/nvk/bitcointreasuries.org/issues?q=is%3Aissue+is%3Aclosed">closed</a> and open issues before creating a new submission, don't submit just an article without any other information.**

**Comment by nvk** [comment]
updated
