### ISSUE TITLE
Argo Blockchain update

### ISSUE THREAD

**Issue by nickchan89** [nvk/bitcointreasuries.org#162]
They are now holding 501 bitcoin as per this RNS https://polaris.brighterir.com/public/argo_blockchain/news/rns/story/ry4z38r

**Comment by nvk** [comment]
what's the summary?

**Comment by nickchan89** [comment]
At the end of January, the company held 501 BTC in Bitcoin and BTC equivalents.

**Comment by nvk** [comment]
sorry, reviewing from the phone I missed the op

**Comment by nvk** [comment]
live https://twitter.com/BTCtreasuries/status/1359207901148172298?s=20
