### ISSUE TITLE
BTCS Inc.

### ISSUE THREAD

**Issue by GermanCryptoGuy** [nvk/bitcointreasuries.org#163]
BTCS Inc.
78.534 BTC

Proof:

https://sec.report/Document/0001493152-21-001796/#form10-k.htm

**Comment by marcodiomede** [comment]
**The Company acquires Digital Assets to provide investors with indirect ownership of Digital Assets that are not securities, such as bitcoin and ether.**  The Company acquires Digital Assets through open market purchases. We are not limiting our assets to a single type of Digital Asset and may purchase a variety of Digital Assets that appear to benefit our investors, subject to the limitations contained within this prospectus regarding Digital Securities. As of January 22, 2021, the Company had the following Digital Assets.
Is this an etf-like?

https://finance.yahoo.com/quote/btcs?ltr=1 symbol of BTCs stocks

**Comment by marcodiomede** [comment]
https://github.com/nvk/bitcointreasuries.org/issues/142
I already posted here. These BTC are not property of the firm and not AUM. So we don't know how to classify

**Comment by GermanCryptoGuy** [comment]
OK
