### ISSUE TITLE
MOGO

### ISSUE THREAD

**Issue by Mikey-Dread** [nvk/bitcointreasuries.org#164]
- MOGO
- NASDAQ:MOGO / TSX:MOGO
- https://www.businesswire.com/news/home/20201223005205/en/Mogo-to-Make-Corporate-Investment-in-Bitcoin
- Bitcoin Purchase Basis price: $1.5m USD @ $23,000 per BTC
- Market Cap: $530.56m CAD
- Total BTC: 50 BTC
- https://mogo.finance/results-and-reports/

BUZZ – Mogo: Jumps on investment in bitcoin
23 Dec 2020
* U.S.-listed shares of Canadian mortgage-focused fintech co up 26.8% at $4.3 premarket
* Co to make an initial investment of C$1.5 mln ($1.16 mln) in bitcoin; may consider additional investments in 2021...
* "We are strong believers in bitcoin as an asset class and believe this investment is consistent with our goal to make bitcoin investing available to all Canadians" - CFO
* Bitcoin hit a record high of $23,000 against the U.S. dollar Dec. 17
* YTD, shares up 32.09%
($1 = 1.2878 Canadian dollars)

(Reporting by Sohini Podder in Bengaluru) ((sohini.podder@thomsonreuters.com)
 Copyright 2021 Thomson Reuters. Click for restrictions.

**Comment by nvk** [comment]
Added
