### ISSUE TITLE
Update on Grayscale Large Cap, 3iq Bitcoin Fund, ETC Bitcoin Group ETP

### ISSUE THREAD

**Issue by marcodiomede** [nvk/bitcointreasuries.org#165]
Grayscale Large Cap  7369 BTC
https://grayscale.co/digital-large-cap/ 15615 mln x 0,00047369 =7369

3iq Bitcoin Fund   TSX:QBTC.U   23363 BTC
https://3iq.ca/the-bitcoin-fund/

ETC bitcoin Group ETP   BTCE:GR   13438
 https://btc-etc.com/products/btcetc.html 13625754 shares x 0.00098625 BTC per unit =13438 BTC
 
 Ps: remove mt.gox from the list. They already returned their BTC to Mt.Gox's customers

**Comment by nvk** [comment]
>Ps: remove mt.gox from the list. They already returned their BTC to Mt.Gox's customers

Do you have a link/source for that?

**Comment by marcodiomede** [comment]
https://www.coindesk.com/mt-gox-creditors-can-claim-90-of-bitcoin-owed-under-pact-reached-with-coinlab-bloomberg

**Comment by nvk** [comment]
Any updates if the disposition is complete?

**Comment by marcodiomede** [comment]
It is unclear. It seems that the agreement for investors refund is still not effective.
I suggest to leave mt.gox on the website for the time being; Should I find more info, I will open a new issue.

**Comment by nvk** [comment]
I agree, once its dispersed than we take out.
