### ISSUE TITLE
NEW: Osprey Bitcoin Trust

### ISSUE THREAD

**Issue by obsidience** [nvk/bitcointreasuries.org#167]
- [x] Name: Osprey Bitcoin Trust
- [x] Exchange: OBTC (over the counter)
- [x] https://finance.yahoo.com/quote/OBTC/
- [x] Bitcoin Purchase Basis price: $3787.78USD
- [x] Market Cap: ~$69,693,320 USD
- [x] Total BTC: 1417.1035 BTC
- [x] Financial Report: https://backend.otcmarkets.com/otcapi/company/financial-report/270029/content

https://ospreyfunds.io/
https://www.otcmarkets.com/stock/OBTC/overview

**Comment by marcodiomede** [comment]
You can find updated data here: https://ospreyfunds.io/products/
At the moment they have 4802352 shares * 0.00034148 BTC per share =1639 BTC.
Finally, with public listing, we have more precise data on Osprey.. to be honest, I expected them to have more BTC. Let's see how it grows

**Comment by nvk** [comment]
Added.
