### ISSUE TITLE
I don't see TESLA [TSLA]

### ISSUE THREAD

**Issue by CryptoClive** [nvk/bitcointreasuries.org#168]
- [ ] Name: Coin Citadel OTC
- [ ] Exchange: symbol (NASDA:SQ) or wherever I can find it
- [ ] Link to google finance or wherever I can find it
- [ ] Bitcoin Purchase Basis price: $XXX USD
- [ ] Market Cap: $XXX USD
- [ ] Total BTC: XXX BTC
- [ ] Direct link to latest financial report

**Please review existing <a href="https://github.com/nvk/bitcointreasuries.org/issues?q=is%3Aissue+is%3Aclosed">closed</a> and open issues before creating a new submission, don't submit just an article without any other information.**

**Comment by nvk** [comment]
https://github.com/nvk/bitcointreasuries.org/issues/157
