### ISSUE TITLE
QBTC

### ISSUE THREAD

**Issue by andrei-gavrilov** [nvk/bitcointreasuries.org#17]
1. 3iQ The Bitcoin Fund [TSX:QBTC.U]
2. [Info on NAV and Reports](https://3iq.ca/the-bitcoin-fund/)
3. BTC Holdings:
Units Outstanding * BTC per Unit = 7,347,498 * 0.001129 = 8295 BTC
4. NAV as at October 8, 2020: $91,189,025 USD

**Comment by nvk** [comment]
added, will update live soon.
