### ISSUE TITLE
Add BTCC (Canadian ETF)

### ISSUE THREAD

**Issue by nvk** [nvk/bitcointreasuries.org#170]

**Comment by marcodiomede** [comment]
https://www.purposeinvest.com/funds/purpose-bitcoin-etf
They have 2501 BTC.
Fun fact, yesterday the figure was 85 BTC

Name: Purpose Bitcoin ETF
BTCC-B.TO
https://finance.yahoo.com/quote/BTCC-B.TO?p=BTCC-B.TO 
Bitcoin Purchase Basis price: ?
 Market Cap: ?
 Total BTC: 2501 BTC

**Comment by attacker007** [comment]
They now hold 6036.701599 BTC ...

**Comment by marcodiomede** [comment]
Wow, they are growing really fast. Time for BTC ETF hype? :D

**Comment by nvk** [comment]
Planning on updating monday morning when the market opens

**Comment by nvk** [comment]
added

**Comment by attacker007** [comment]
@nvk now they hold 8288.62 BTC .. Update it. check this link: https://www.purposeinvest.com/funds/purpose-bitcoin-etf

**Comment by attacker007** [comment]
They added more... Now They hold total amount of 9320.01 BTC ..

**Comment by attacker007** [comment]
Update: Current holdings they have   10215.9033 BTC ....
