### ISSUE TITLE
Hut 8 Updated BTC Hodlings

### ISSUE THREAD

**Issue by nachoguru** [nvk/bitcointreasuries.org#171]
Was: 2851
Now: 3012

They haven't updated the list of news releases on their own web site, but Hut 8 had a press release yesterday and pointed to it from their Twitter account: 

https://twitter.com/Hut8Mining/status/1362025866155479052

https://www.newswire.ca/news-releases/hut-8-mining-bitcoin-holdings-surpass-3-012-valued-at-186m-cad-804326405.html

> Hut 8 holds 3,012 bitcoin on its current balance sheet as of 5pm ET on Tuesday February 16, 2021, including 1,000 bitcoin in a Genesis savings account generating a 4% yield in fiat.

>  Based on current network difficulty and Hut 8's current output, the bitcoin production is calculated at approximately 6.8 bitcoin per day

**Comment by nvk** [comment]
updated
