### ISSUE TITLE
Add Digihost Technology Inc. (DGHI.V)

### ISSUE THREAD

**Issue by tealife2050** [nvk/bitcointreasuries.org#172]
Publicly traded - Yes
Exchange - TSX Venture
Ticker - DGHI.V
BTC held - 183.7 
Announcement date - 04 Feb 2021
Value reported on 04 Feb 2021 - USD 6,890,000
Source - SEDAR regulatory filing (04 Feb News Release link below)
https://www.sedar.com/DisplayCompanyDocuments.do?lang=EN&issuerNo=00043472

**Comment by nvk** [comment]
added

**Comment by tealife2050** [comment]
Thank you, can you please edite the name to "Digihost Technology Inc" instead of "Add Digihost Technology Inc". Thanks
