### ISSUE TITLE
Marathon Patent Group  

### ISSUE THREAD

**Issue by Jwassad** [nvk/bitcointreasuries.org#178]
Marathon Patent Group 
MARA (NASDAQ) 
https://www.google.com/finance/quote/MARA:NASDAQ
Bitcoin Purchase Basis price: $31,200 USD / https://www.marathonpg.com/news/press-releases/detail/1224/marathon-invests-150-million-in-bitcoin
Market Cap: $4B USD
Total BTC: 4812 BTC
https://ir.marathonpg.com/quarterly-reports#document-25104-0001493152-20-021199

**Please review existing <a href="https://github.com/nvk/bitcointreasuries.org/issues?q=is%3Aissue+is%3Aclosed">closed</a> and open issues before creating a new submission, don't submit just an article without any other information.**

**Comment by nvk** [comment]
already there

**Comment by Jwassad** [comment]
Thanks. J
-------- Original message --------From: nvk <notifications@github.com> Date: 2/21/21  9:21 PM  (GMT-05:00) To: "nvk/bitcointreasuries.org" <bitcointreasuries.org@noreply.github.com> Cc: Jwassad <jwassad@bellsouth.net>, Author <author@noreply.github.com> Subject: Re: [nvk/bitcointreasuries.org] Marathon Patent Group   (#178) 
already there
