### ISSUE TITLE
Update BIGG Digital Assets Inc to 300 BTC

### ISSUE THREAD

**Issue by markgukov** [nvk/bitcointreasuries.org#179]
Hi,

BIGG has added 60.7 BTC @ USD$44,970 to reach 300 BTC.

https://financialpost.com/globe-newswire/bigg-digital-assets-inc-purchases-additional-60-7-bitcoins-for-netcoins-operational-float-total-bitcoin-treasury-reaches-300-btc

Thanks

**Comment by nvk** [comment]
updated.thx!
