### ISSUE TITLE
Coin Citadel - information provided is from 2015. Need updated information

### ISSUE THREAD

**Issue by Jsupp104** [nvk/bitcointreasuries.org#181]
- [ ] Name: Coin Citadel OTC
- [ ] Exchange: symbol (OTCMKTS:CCTL)
- [ ] https://finance.yahoo.com/quote/CCTL?p=CCTL
- [ ] Bitcoin Purchase Basis price is unknown
- [ ] Market Cap: $XXX USD
- [ ] Total BTC: XXX BTC
- [ ] https://backend.otcmarkets.com/otcapi/company/financial-report/271014/content

**Please review existing <a href="https://github.com/nvk/bitcointreasuries.org/issues?q=is%3Aissue+is%3Aclosed">closed</a> and open issues before creating a new submission, don't submit just an article without any other information.**

**Comment by Jsupp104** [comment]
New reports from 2018 and 2019 do not show amount of bitcoin in their treasuries.

**Comment by weex** [comment]
Confirmed the linked pdf makes no mention of a current Bitcoin holding. Lists 500+ btc purchased in 2015, but current digital assets of only $24k which is a few btc at most. https://www.otcmarkets.com/stock/CCTL/financials also lists no cash equivalents of note.

**Comment by Jsupp104** [comment]
Unfortunately, Fortune used https://bitcointreasuries.org/ as a source when they wrote an article about public companies that hold bitcoin on their books.

**Comment by nvk** [comment]
no deeetz
