### ISSUE TITLE
Square purchased approximately 3,318 bitcoins at an aggregate purchase price of $170 million

### ISSUE THREAD

**Issue by Djo1e** [nvk/bitcointreasuries.org#182]
- [x] Name: Square, Inc
- [x] Exchange: NASDA:SQ
- [x] Google finance link: https://www.google.com/finance/quote/SQ:NYSE
- [x] Bitcoin Purchase Basis price: $51,235 USD
- [x] Market Cap: $115.71B USD
- [x] Total BTC: 3,318 BTC
- [x] Direct link to latest financial report: https://investors.squareup.com/financials/quarterly-results/default.aspx

**Comment by FracturedWinter** [comment]
Should be labelled as UPDATING. Square is already in the list: #13

**Comment by Djo1e** [comment]
My bad, thanks @FracturedWinter. It's seems I can't change it now.

**Comment by nvk** [comment]
I’m afk, what’s the new Confirmed total?

**Comment by Djo1e** [comment]
@nvk They added 3,318, making the total 8,027.

**Comment by nvk** [comment]
Live
