### ISSUE TITLE
MicroStrategy, Inc. Update

### ISSUE THREAD

**Issue by Kapot** [nvk/bitcointreasuries.org#183]
MicroStrategy® Incorporated (Nasdaq: MSTR) (...), (...), today announced that it had purchased an additional approximately 19,452 bitcoins for approximately $1.026 billion in cash at an average price of approximately $52,765 per bitcoin, inclusive of fees and expenses. 

https://www.microstrategy.com/en/investor-relations/press/microstrategy-acquires-additional-19452-bitcoins-for-1-026-billion_02-24-2021

**Comment by nvk** [comment]
live https://twitter.com/BTCtreasuries/status/1364591106994880512?s=20
