### ISSUE TITLE
NASDAQ:MSTR

### ISSUE THREAD

**Issue by galaxypikachu** [nvk/bitcointreasuries.org#184]
- [x] Name: MicroStrategy Incorporated
- [x] Exchange: NADQ:MSTR
- [x] NADQ:MSTR
- [x] Bitcoin Purchase Basis price: $2.171 billion USD
- [x] Market Cap: $7 billion USD
- [x] Total BTC: 90531 BTC
- [x] https://news.bitcoin.com/microstrategy-buys-1-billion-more-bitcoin-90000-btc/
- [x] https://www.microstrategy.com/en/investor-relations/press/microstrategy-acquires-additional-19452-bitcoins-for-1-026-billion_02-24-2021

**Please review existing <a href="https://github.com/nvk/bitcointreasuries.org/issues?q=is%3Aissue+is%3Aclosed">closed</a> and open issues before creating a new submission, don't submit just an article without any other information.**

**Comment by nvk** [comment]
live https://twitter.com/BTCtreasuries/status/1364591106994880512?s=20
