### ISSUE TITLE
TSX: EBIT - Evolve Bitcoin ETF

### ISSUE THREAD

**Issue by TheAncientAnimal** [nvk/bitcointreasuries.org#185]
- [ ] Name: Evolve Bitcoin ETF
- [ ] Exchange: (TSX: EBIT [CAD]), (TSX: EBIT.U [USD])
- [ ] Link: https://evolveetfs.com/product/ebit/ or https://money.tmx.com/en/quote/EBIT.U
- [ ] Bitcoin Purchase Basis price: $20 USD
- [ ] Market Cap: $1,989,204 USD
- [ ] Total BTC: 38.44 BTC
- [ ] Direct link to latest financial report: https://evolveetfs.com/wp-content/uploads/holdings/EBIT.csv

**Comment by nvk** [comment]
Too small, let’s wait till it grows a little

**Comment by marcodiomede** [comment]
It has 568 BTC now

**Comment by nvk** [comment]
added
