### ISSUE TITLE
Bitcoin Group SE "info on this AUM" is dead

### ISSUE THREAD

**Issue by torkelrogstad** [nvk/bitcointreasuries.org#187]

**Comment by marcodiomede** [comment]
https://bitcoingroup.com/images/PDF/FB_2020/BitcoinGroup_HJB2020_EN.pdf
Theyr financial report for mid 2020 states that they held cryptocurrencyes for 33 milion USD (as of 30 june 2020) but there is no further information about the compositions of these holdings

**Comment by nvk** [comment]
we can wait for their next one till we make the next change

**Comment by torkelrogstad** [comment]
We don't have any numbers on their BTC stack, though. They've only given fiat numbers, and very little to go on for estimating it, unlike Tesla
