### ISSUE TITLE
Measure of Institutions over time?

### ISSUE THREAD

**Issue by TorokNRoll** [nvk/bitcointreasuries.org#188]
Hi!

this is a great table!  thanks!

No issue, just a proposal:  It would be great to have a measure of the count of institutions added to this list over time.

Cheers,
Steve

**Please review existing <a href="https://github.com/nvk/bitcointreasuries.org/issues?q=is%3Aissue+is%3Aclosed">closed</a> and open issues before creating a new submission, don't submit just an article without any other information.**

**Comment by nvk** [comment]
not possible atm
