### ISSUE TITLE
Add Voyager Digital

### ISSUE THREAD

**Issue by Jaimegarcia02** [nvk/bitcointreasuries.org#19]
Voyager Digital is a publicly-traded company that holds Bitcoin. 

CSE: VYGR is traded on the Canadian Securities Exchange (CSE).
Additionally, an Over-the-Counter (OTC) version of our stock is available across many US brokers and can be purchased via the VYGVF symbol.
https://www.investvoyager.com/investorrelations/overview/

Link to SEDAR Report.
https://t.co/UTA7llOldK?amp=1

Total BTC held: 1239 as of March 31, 2020.

[VOYAGER DIGITAL (CANADA) LTD.pdf](https://github.com/nvk/bitcointreasuries.org/files/5358077/VOYAGER.DIGITAL.CANADA.LTD.pdf)

**Comment by nvk** [comment]
Please see the format. 

1. MUST be publicaly traded, include symbol and reputable exchange (ie NASDAQ)
2. MUST include filing or announcement link
3. MUST include total BTC held in Treasuries
4. MUST include purchase price and/or total in the balance sheet as of last filing in USD
5. IF you have ALL those items create an issue here

**Comment by nvk** [comment]
Thanks! What was the basis price for the 1239 BTC?

**Comment by Jaimegarcia02** [comment]
Not sure, as it acquired through the Ethos acquisition back in Nov of 2019.

**Comment by nvk** [comment]
I can't find "Bitcoin" on their reports, maybe I'm missing something?

**Comment by Jaimegarcia02** [comment]
It's on page 10. Bitcoin was acquired when Voyager Digital acquired Ethos.io <http://ethos.io/> in 2019. 
On page 10, it list all of the tokens that were acquired by the acquisition. 
Bitcoin is the first on the list as BTC.

**Comment by nvk** [comment]
I only found this BTC mention which is equivalent to 717 BTC in Today's amount.
![image](https://user-images.githubusercontent.com/797193/95640401-9eaed080-0a6a-11eb-9bdd-26de6ae0233c.png)

**Comment by nvk** [comment]
I'm just trying to understand how did you get to the 1239 amount?

**Comment by Jaimegarcia02** [comment]
On March 31st, Bitcoin was trading around $6,400 dollars. I divided $7,927,182 by the price of Bitcoin on March 31st.

**Comment by nvk** [comment]
Ok, I will go with that. Will be live soon.

**Comment by Jaimegarcia02** [comment]
Does this mean that Voyager will be added?

**Comment by nvk** [comment]
Yes, it's live. If you can come back with accurate basis prices would be much appreciated. Thanks for the submission :)

**Comment by Jaimegarcia02** [comment]
Thank you! 

Cordially,
Jaime Garcia
