### ISSUE TITLE
Update on two bitcoin ETFs: Purpose and ETC group bitcoin 

### ISSUE THREAD

**Issue by marcodiomede** [nvk/bitcointreasuries.org#190]
Purpose Bitcoin ETF - BTCC they have 11141 BTC 
https://www.purposeinvest.com/funds/purpose-bitcoin-etf

ETC bitcoin Group ETP BTCE:GR 19517 BTC
https://btc-etc.com/products/btcetc.html 19812840 shares x 0,00098511 BTC per unit =19517 BTC

**Comment by nvk** [comment]
updated, thank you!
