### ISSUE TITLE
BitGo New Entry

### ISSUE THREAD

**Issue by promitq** [nvk/bitcointreasuries.org#191]
- [ ] Name: BitGo
- [ ] Exchange: Private
- [ ] https://www.coindesk.com/bitgo-reveals-250m-in-bitcoin-holdings
- [ ] Bitcoin Purchase Basis price: $XXX USD
- [ ] Market Cap: $250M USD
- [ ] Total BTC: XXX BTC
- [ ] https://www.coindesk.com/bitgo-reveals-250m-in-bitcoin-holdings
- [ ] 
**Please review existing <a href="https://github.com/nvk/bitcointreasuries.org/issues?q=is%3Aissue+is%3Aclosed">closed</a> and open issues before creating a new submission, don't submit just an article without any other information.**

**Comment by nvk** [comment]
A bit tenuous, any more sources?

**Comment by promitq** [comment]
No brother.. No other sources. I follow bitcointreasuries.org everyday, so when I found out the news, I tried to cross-check. Couldn't find it.

**Comment by nvk** [comment]
no deetz
