### ISSUE TITLE
NEW ENTRY

### ISSUE THREAD

**Issue by 521314** [nvk/bitcointreasuries.org#192]
Name:Bit Digital, Inc.
NASDAQ:BTBT

Announcement link : https://bit-digital.com/press-releases
Official website : https://www.bit-digital.com/
Mining website : https://bit-digital.com/bitcoin-mining/

1934.89 btc on January 31,2021

(Financial report reference : https://www.sec.gov/Archives/edgar/data/1710350/000121390020043684/ea131995ex99-1_bitdigital.htm)

As of the filing date on December 18,2020, We have earned an aggregation of 1331.2 bitcoins and recognized unaudited revenues of approximately $16.50 million. The averaged purchase price is $16.50 Million / 1331.2 = $12,394.

Market Capitalization : $744.679M

**Comment by marcodiomede** [comment]
Most of the BTC mined were sold. In their latest press release they state that they have 488.5 BTC

https://bit-digital.com/press-releases/bit-digital-announces-bitcoin-mining-production-of-424-7-bitcoin-for-january-2021/
"NEW YORK, March 2, 2021 /PRNewswire/ — Bit Digital, Inc. (Nasdaq: BTBT), an emerging bitcoin mining company headquartered in New York, announced its unaudited Bitcoin production data for the month ended January 31, 2021. During the month, the company earned 424.7 bitcoins, accounting for approximately $14.8 million in revenue. As of January 31, 2021, the company held 488.5 bitcoins in treasury, versus 262.6 bitcoins as of December 31, 2021."
