### ISSUE TITLE
Bit Digital, Inc.

### ISSUE THREAD

**Issue by BitDigitalBTBT** [nvk/bitcointreasuries.org#193]
Name:Bit Digital, Inc.
NASDAQ:BTBT

Announcement link : https://bit-digital.com/press-releases
Official website : https://www.bit-digital.com/
Mining website : https://bit-digital.com/bitcoin-mining/

As of January 31, 2021, the company has mined 1,934.89 btc and holds 488.5 btc
(reference : https://bit-digital.com/press-releases/bit-digital-announces-bitcoin-mining-production-of-424-7-bitcoin-for-january-2021/)

(Financial report reference : https://www.sec.gov/Archives/edgar/data/1710350/000121390020043684/ea131995ex99-1_bitdigital.htm)

As of the filing date on December 18,2020, We have earned an aggregation of 1331.2 bitcoins and recognized unaudited revenues of approximately $16.50 million. The averaged purchase price is $16.50 Million / 1331.2 = $12,394.

Market Capitalization : $646.189M

**Comment by nvk** [comment]
live
