### ISSUE TITLE
AKER ASA (Seetee AS)

### ISSUE THREAD

**Issue by xploddan** [nvk/bitcointreasuries.org#199]
Name: Seetee AS - https://www.seetee.io/ (Subsidiary of Aker ASA)
Exchange: AKER:NO (OSLO BØRS) (This is the Parent company holding 90.01% of the shares of Seetee TopCo AS which owns 100% of Seetee AS)
https://www.bloomberg.com/quote/AKER:NO
Bitcoin Purchase Basis price: $50,085 USD (approx. of $58.6B USD initial capitalisation and stated 1,170 BTC holdings)
https://www.akerasa.com/en/news/stock-exchange-releases/article/36900-aker-asa-launches-seetee-to-invest-in-bitcoin-and-blockchain-technology
Market Cap: $6.2B USD (Parent company Aker ASA)
Total BTC: 1,170 BTC
Direct link to latest financial report (First Shareholder letter):
https://www.seetee.io/static/shareholder_letter-6ae7e85717c28831bf1c0eca1d632722.pdf

**Comment by nvk** [comment]
live, thx!

**Comment by xploddan** [comment]
Here is Google finance link

https://www.google.com/finance/quote/AKAAF:OTCMKTS
