### ISSUE TITLE
DigitalX (ASX)

### ISSUE THREAD

**Issue by FaysalM** [nvk/bitcointreasuries.org#20]
**Company Name:** DigitalX
**Country**: AU
**SYMBOL**: ASX: DCC
**Purchases / Filings**: [November 2019](https://clients3.weblink.com.au/pdf/DCC/02286540.pdf)
**Total in USD at Ann**: 874835
**Todays Value**: 2,451,000
**Bitcoin**: 215

Latest Annual Shareholders report here:
https://clients3.weblink.com.au/pdf/DCC/02286540.pdf

Currently listed on ASX (Australia). 
Bitcoin Fund Seeded with 215 bitcoins in November 2019

Press Release Here:
https://clients3.weblink.com.au/pdf/DCC/02286540.pdf

You may also want to reach out to them here: https://twitter.com/DigitalXLtd
Can also reach out to me here: https://twitter.com/3L3C70

p.s. Thanks for the website, I had just started on the exact same thing before you beat me to it, and this looks much better than what I was going to do anyways.

**Comment by nvk** [comment]
Thanks! added https://twitter.com/nvk/status/1314907379973197824?s=20
