### ISSUE TITLE
Add DCG once there is a clear amount of BTC

### ISSUE THREAD

**Issue by ViktorBohu** [nvk/bitcointreasuries.org#204]
DCG bought/will buy 250M$ worth of BTC as GBTC shares

https://www.businesswire.com/news/home/20210310005273/en/Digital-Currency-Group-Announces-Plan-to-Purchase-Shares-of-Grayscale-Bitcoin-Trust-OTCQX-GBTC

**Comment by nvk** [comment]
That's double accounting, we already have GBTC's coins
