### ISSUE TITLE
Galaxy Digital Market Cap

### ISSUE THREAD

**Issue by rororaq86** [nvk/bitcointreasuries.org#209]
The Galaxy Digital market cap is wrong when compared to the bitcoin holdings.

GDH Ltd owns a 22.5% interest in GDH LP, which owns the bitcoin assets.

Therefore, the proper share count to use is the fully diluted share count that appears on the balance sheet of Galaxy Digital Holdings Ltd, which is 298,054,925. At an $18 share price, this is 5,364mm (5.4bn). 

You can verify this on https://assets.ctfassets.net/rbgwch8v5pod/147tfWoeXtNfa5ciQIEz5o/a0cf35cde0db2cc072faf3c6906c89ec/GDH_Ltd_Financial_Statements_Q3_20_FINAL.pdf

and 

https://assets.ctfassets.net/rbgwch8v5pod/kHwjYnElTyMHrpKytBcLQ/f60c08a5eff8b4870bb944c8a81744a0/GDH_LP_Financial_Statements_Q3_20_FINAL.pdf

best,
Roro86

**Comment by nvk** [comment]
You might want to reach out to Google Finance, that's where we are sourcing the data.

**Comment by nvk** [comment]
updated.
