### ISSUE TITLE
BTCE

### ISSUE THREAD

**Issue by as-is2376** [nvk/bitcointreasuries.org#21]
Instrument Name: BTCE
Type: ETC 
Country: DE

Total Holdings (Number of Bitcoin) | 5215.159
https://www.hanetf.com/product/8/fund/btcetc-bitcoin-exchange-traded-crypto-btce

**Comment by nvk** [comment]
Is this OTC? Is this held or assets u SDR management?
What was their basis price for the BTC?

**Comment by as-is2376** [comment]
1. not OTC, It's an exchange traded commodity (ETF like) tradable in many european stock exchanges
2. Held asset through a Custodian (BitGO Trust Company) underlying asset can be redeemed (https://btc-etc.com/resources/EN_Redemption_Information_Document_BTCetc.pdf)
3. Hard to tell since it constantly updates as  money flows in, nonetheless 70% of the holdings were added between July 20th and Aug 8th (https://www.hanetf.com/UsersFiles/HanETF/Documents/452/20201008_BTCE_NAV_History.xlsx), so i would say that average price is around 11k$

**Comment by nvk** [comment]
Thanks. Added, will be live soon.
