### ISSUE TITLE
Meitu, Inc. Update

### ISSUE THREAD

**Issue by FracturedWinter** [nvk/bitcointreasuries.org#210]
On March 17, 2021, Miracle Vision had, pursuant to the Cryptocurrency Investment Plan, further acquired in open market transactions 386.08581655 units of Bitcoin at an aggregate consideration of approximately US$21.6 million.

Source:
https://www1.hkexnews.hk/listedco/listconews/sehk/2021/0317/2021031701432.pdf

Supporting press coverage:
https://www.theblockcrypto.com/linked/98632/meitu-subsidiary-50m-crypto-purchase

Previous Issue:
#196

**Comment by nvk** [comment]
updated
