### ISSUE TITLE
U forgot the german company Bitcoin Group SE

### ISSUE THREAD

**Issue by nbchiller** [nvk/bitcointreasuries.org#211]
The publicly traded german company Bitcoin Group SE which is basically an ebay for cryptos with over 15mio customers has 
4.000 own bitcoins and some ether!
That would bring them to place 6 in your ranking!

**Comment by nvk** [comment]
Do we have some public info about it?

**Comment by BitcoinInvestor123** [comment]
I have opened a new issue some minutes ago about Bitcoin Group SE with detailed information and links.
