### ISSUE TITLE
Bitcoin Group $ADE.DE

### ISSUE THREAD

**Issue by BitcoinInvestor123** [nvk/bitcointreasuries.org#213]
- [ ] Name: Bitcoin Group SE
- [ ] Exchange: symbol ADE.DE
- [ ] Link to google finance or wherever I can find it: https://de.finance.yahoo.com/quote/ADE.DE/
- [ ] Bitcoin Purchase Basis price: not disclosed
- [ ] Market Cap: 268m EURO or 320m USD (5 million stocks outstanding)
- [ ] Total BTC: 4000 BTC
- [ ] Direct link to latest financial report: https://bitcoingroup.com/images//PDF/FB_2020/BitcoinGroup_HJB2020.pdf

I know that Bitcoin Group is already listed. Nevertheless, there are several mistakes and I think you should correct this. First of all, the company is not ETF like as suggested, it is a company with significant cryptocurrency holdings and it is operating the german crypto marketplace bitcoin.de. So it is a publicly-traded company like square etc., and it is listed in Germany under the ticker $ADE.DE. Furthermore, bitcointreasuries says that the company holds 2,074 BTC. This is not correct: they hold 4000 BTC!
On February 23, the company disclosed that its cryptocurrency holdings are worth more than €170m (see https://bitcoingroup.com/de/corporatenews/2021/bitcoin-group-se-verzeichnet-zuwachs-von-518-beim-eigenbestand-an-krypto-assets-auf-eur-170-mio). In this interview (11th of March) with the founder of Bitcoin Group, he says that the company holds 4000 bitcoins (https://omr.com/de/oliver-flaskaemper-omr-podcast-bitcoin-de-adbutler/). With a BTC price of $59k, their bitcoin holdings are worth $236m.

**Comment by nvk** [comment]
updated

did you find our the cost basis for the BTC?

**Comment by BitcoinInvestor123** [comment]
Thanks. No, unfortunately not. What I know is, that it was just a fraction of the current value. Unless they publish that number, we will probably never know because they accumulated the bitcoins over a longer time frame (several years).
