### ISSUE TITLE
Reconsidering VanEck Vectors Bitcoin ETN

### ISSUE THREAD

**Issue by alelorca** [nvk/bitcointreasuries.org#214]
- [ ] Name: VanEck Vectors Bitcoin ETN
- [ ] Exchange: XETRA:VBTC DE000A28M8D0
- [ ] Yahoo finance: https://finance.yahoo.com/quote/DE000A28M8D0.SG
- [ ] Basis price: $XXX USD (It's open-end ETN, so )
- [ ] Market Cap: $182.9M USD (today)
- [ ] Total BTC: 3072 BTC (as of 28 Feb 2021)
- [ ] Link: https://www.vaneck.com/de/en/etf/digital-assets/vbtc/overview

Previously discarded due to low volume on https://github.com/nvk/bitcointreasuries.org/issues/85 but now is much larger.

**Comment by alelorca** [comment]
Update: 3135 BTC as of 19 Mar 2021 according to
https://www.vaneck.com/de/en/etf/digital-assets/vbtc/holdings

**Comment by nvk** [comment]
live

**Comment by nvk** [comment]
ann https://twitter.com/BTCtreasuries/status/1374012073781383168?s=20
