### ISSUE TITLE
DMG Blockchain Technology

### ISSUE THREAD

**Issue by jtsangeng** [nvk/bitcointreasuries.org#215]
Hi, DMG Blockchain Solutions Inc. (TSX-V: DMGI) (DMGGF:OTCQB US) (FRANKFURT:6AX) , a publicly traded company recently added Bitcoin to its treasuries as per the news alert below.

https://www.globenewswire.com/news-release/2021/03/18/2195465/0/en/DMG-Increases-its-Bitcoin-Exposure-by-Accumulating-Additional-BTC-for-its-Treasury.html

**Comment by nvk** [comment]
Do we have more info on the total, cost basis, etc?

**Comment by nvk** [comment]
I can't find the total

**Comment by jtsangeng** [comment]
If you look at the March 18 2021 SEDAR Filings, there is a news release that states that they have 220 BTC.
I've attached the news release.
You can check on the SEDAR website as well.
Let me know if you have any issues.
Jay
    On Friday, March 26, 2021, 10:16:02 a.m. EDT, nvk ***@***.***> wrote:  
 
 


I can't find the total

**Comment by jtsangeng** [comment]
Unfortunately I don't know the total cost basis as it was not stated in the news release.  However, I've attached the submission from SEDAR filings stating 220 BTCs.

[DMG March 18, 2021 News release.pdf](https://github.com/nvk/bitcointreasuries.org/files/6214759/DMG.March.18.2021.News.release.pdf)

**Comment by nvk** [comment]
added
