### ISSUE TITLE
Bitfarm ($BITF/$BFARF) update

### ISSUE THREAD

**Issue by UltimateJatt** [nvk/bitcointreasuries.org#216]
Bitcoin inventory increased to 489.
Average cost is $7,000 USD

https://ca.finance.yahoo.com/news/bitfarms-announces-installed-hashrate-1-110000249.html
https://thedeepdive.ca/bitfarms-grows-hashrate-to-1-3-eh-s-with-latest-purchase/

**Comment by nvk** [comment]
updated
