### ISSUE TITLE
Check my numbers on AUM products

### ISSUE THREAD

**Issue by nvk** [nvk/bitcointreasuries.org#217]
I've updated some, please double check.

GBTC 649,130 => 654,885 BTC
Purpose Bitcoin ETF 11,141 => 14,660 BTC
Bitwise 10 Crypto Index Fund 11,430 => 13,650 BTC 
3iQ The Bitcoin Fund 23,363 => 46,363 BTC 
ETC Group Bitcoin ETP 19,517 => 21,342 BTC 
Evolve Bitcoin ETF 568 => 1,457 BTC

**Comment by FracturedWinter** [comment]
Do you have links to the source of the updates easily available to simplify the task?

Either way, first two look good. 

1) GBTC 649,130 => 654,885 BTC
March 23, 2021: 692,370,100 * 0.00094586
Source: https://grayscale.co/bitcoin-trust/
<img width="317" alt="GBTC" src="https://user-images.githubusercontent.com/20613574/112466313-1bddb180-8d3c-11eb-9fa2-d70b950928a6.png">


2) Purpose Bitcoin ETF 11,141 => 14,660 BTC
March 23, 2021: 14659.9895 BTC
Source: https://www.purposeinvest.com/funds/purpose-bitcoin-etf
<img width="530" alt="Purpose" src="https://user-images.githubusercontent.com/20613574/112466326-1f713880-8d3c-11eb-9ebf-dbee1637110b.png">

**Comment by nvk** [comment]
https://www.bitwiseinvestments.com/funds/Bitwise-10
https://3iq.ca/the-bitcoin-fund-qbtcu-qbtc/
https://evolveetfs.com/product/ebit/

**Comment by FracturedWinter** [comment]
Have differences on the remaining funds outlined below. 3iQ looks like maybe a double-counting issue? 

**3. Bitwise 10 Crypto Index Fund 11,430 => 13,650 BTC**
Shares outstanding * XBT per share  = Total BTC
19,754,713 * 0.0006886654 = 13,604

Source: https://www.bitwiseinvestments.com/funds/Bitwise-10
<img width="861" alt="Bitwise" src="https://user-images.githubusercontent.com/20613574/112494855-c0bab780-8d59-11eb-9b20-7b68b0448995.png">
<img width="507" alt="BItwise2" src="https://user-images.githubusercontent.com/20613574/112494875-c3b5a800-8d59-11eb-857f-28e4f65e6ddc.png">


**4. 3iQ The Bitcoin Fund 23,363 => 46,363 BTC**
Units outstanding * BTC per unit  = Total BTC
20,963,216 * 0.00112404 = 23,563.49

Source: https://3iq.ca/the-bitcoin-fund-qbtcu-qbtc/
<img width="1207" alt="QBTC" src="https://user-images.githubusercontent.com/20613574/112495382-3b83d280-8d5a-11eb-92ea-e8e34baaae4c.png">

**5. ETC Group Bitcoin ETP 19,517 => 21,342 BTC**
Total Holdings: 22,014.731 
*Varies slightly from total units and BTC/unit math.

Source: https://www.btc-etc.com/products/btcetc/
<img width="367" alt="ETC Group" src="https://user-images.githubusercontent.com/20613574/112496047-d086cb80-8d5a-11eb-8510-d214f6074595.png">


**6. Evolve Bitcoin ETF 568 => 1,457 BTC**
AUM / NAV * BTC PER SHARE = Total BTC 
$85,790,000 / $27.24 * 0.00038497 = 1,212.42

Source: https://evolveetfs.com/product/ebit/
<img width="971" alt="Evolve" src="https://user-images.githubusercontent.com/20613574/112497044-9f5acb00-8d5b-11eb-84af-d220c54aa076.png">

**Comment by nvk** [comment]
I agree, I double checked iQ3 and you are correct. thx.
