### ISSUE TITLE
Adding sort functionality to the list

### ISSUE THREAD

**Issue by efecini** [nvk/bitcointreasuries.org#22]
It would be good fucntionality to sort the list based on

- Company Name
- Total in USD @Ann
- Today's Value
- Bitcoin
- Base Price(coming soon I suppose)

@nvk maybe you can easily do that on the original google sheet somehow because I know you don't want to add Js to the project.

**Comment by nvk** [comment]
Not possible to freeze footer row on Google Spreadsheet
