### ISSUE TITLE
Banxa Holdings Inc

### ISSUE THREAD

**Issue by slashiiii** [nvk/bitcointreasuries.org#220]
- [ ] Name: Banxa Holdings Inc
- [ ] Exchange: BNXAF
- [ ] https://stocktwits.com/symbol/BNXAF
- [ ] Bitcoin Purchase Basis price: ?
- [ ] Market Cap: $157.21m  USD
- [ ] Total BTC: 136 BTC
- [ ] https://www.newswire.ca/news-releases/banxa-reports-second-quarter-financial-results-and-record-setting-revenue-862865349.html

**Please review existing <a href="https://github.com/nvk/bitcointreasuries.org/issues?q=is%3Aissue+is%3Aclosed">closed</a> and open issues before creating a new submission, don't submit just an article without any other information.**

**Comment by nvk** [comment]
Added, thanks!
