### ISSUE TITLE
BTCS Inc.

### ISSUE THREAD

**Issue by cwallen93117** [nvk/bitcointreasuries.org#222]
- Name: BTCS Inc.
- Exchange: symbol (OTCQB: BTCS)
- https://finance.yahoo.com/quote/btcs?ltr=1
- Bitcoin Purchase Basis price: Various.  BTC and ETH carrying values are combined and carried at lowest price since purchase.  Current value on balance sheet for both ETH and BTC as of last 10k (12/31/2020) is $995,652USD
- Market Cap: $54m USD (https://www.google.com/finance/quote/BTCS:OTCMKTS, yahoo finance has wrong share count)
- Total BTC: 78.534 BTC (as of 1/22/2021)
- Total ETH: 7,680 ETH (as of 3/8/2021) - https://finance.yahoo.com/news/btcs-ethereum-2-0-staking-130400502.html
- Direct link to latest financial report:  https://www.sec.gov/Archives/edgar/data/1436229/000149315221001796/form10-k.htm page 3

**Please review existing <a href="https://github.com/nvk/bitcointreasuries.org/issues?q=is%3Aissue+is%3Aclosed">closed</a> and open issues before creating a new submission, don't submit just an article without any other information.**

**Comment by nvk** [comment]
It's not clear is this a Trust for NAV time product?

**Comment by cwallen93117** [comment]
No its an operating company with a crypto treasury more info here: https://www.btcs.com/#about.   Similar to a Mara or Riot except (much smaller) and instead of mining BTC it currently runs nodes on ETH beacon chain.  Company has BTC and ETH on balance sheet as part of its treasury strategy.

**Comment by cwallen93117** [comment]
Not a trust NAV time product.

**Comment by nvk** [comment]
added
