### ISSUE TITLE
OTCQB: INVU

### ISSUE THREAD

**Issue by handsontrader** [nvk/bitcointreasuries.org#223]
Curious if anyone has looked into Investview - INVU - they mine under a subsidiary Safetek...
https://finance.yahoo.com/news/investview-invu-reports-record-2-143000991.html?.tsrc=rss

**Comment by nvk** [comment]
Haven't do you have more details?

**Comment by handsontrader** [comment]
They have a fair amount of information on their web site…  they are mining under their subsidiary Safetek, appear to be reinvesting..  Their latest 10Q shows revenue from mining and I believe they are holding Bitcoin as well

I am currently going thru their 10Q to see how much they are holding

 

 

https://investview.com

 

 

https://www.sec.gov/Archives/edgar/data/862651/000149315221003898/form10-q.htm

 

 

 

From: nvk ***@***.***>
Reply-To: "nvk/bitcointreasuries.org" ***@***.***>
Date: Monday, March 29, 2021 at 7:57 AM
To: "nvk/bitcointreasuries.org" ***@***.***>
Cc: handsontrader ***@***.***>, Author ***@***.***>
Subject: Re: [nvk/bitcointreasuries.org] Bitcoin Treasuries (#223)

 

Haven't do you have more details?

**Comment by nvk** [comment]
Wanna try to resubmit in this format to make sure we have most things? https://github.com/nvk/bitcointreasuries.org/issues/new?assignees=&labels=NEW+ENTRY&template=new-submission-template.md&title=

**Comment by handsontrader** [comment]
Sure will try and do so.. should I close the other ?

 

 

 

From: nvk ***@***.***>
Reply-To: "nvk/bitcointreasuries.org" ***@***.***>
Date: Monday, March 29, 2021 at 8:09 AM
To: "nvk/bitcointreasuries.org" ***@***.***>
Cc: handsontrader ***@***.***>, Author ***@***.***>
Subject: Re: [nvk/bitcointreasuries.org] OTCQB: INVU (#223)

 

Wanna try to resubmit in this format to make sure we have most things? https://github.com/nvk/bitcointreasuries.org/issues/new?assignees=&labels=NEW+ENTRY&template=new-submission-template.md&title=

**Comment by nvk** [comment]
yeah, I will close this one. Thank you!

**Comment by handsontrader** [comment]
I have not submitted, still doing some research.  My initial request was if anyone had heard about this company and BTC mining..  I will do some additional research and if valid, perhaps resubmit

 

 

 

From: nvk ***@***.***>
Reply-To: "nvk/bitcointreasuries.org" ***@***.***>
Date: Monday, March 29, 2021 at 8:09 AM
To: "nvk/bitcointreasuries.org" ***@***.***>
Cc: handsontrader ***@***.***>, Author ***@***.***>
Subject: Re: [nvk/bitcointreasuries.org] OTCQB: INVU (#223)

 

Wanna try to resubmit in this format to make sure we have most things? https://github.com/nvk/bitcointreasuries.org/issues/new?assignees=&labels=NEW+ENTRY&template=new-submission-template.md&title=
