### ISSUE TITLE
21Shares updated BTC holdings as of March 29, 2021

### ISSUE THREAD

**Issue by EliezerNdinga** [nvk/bitcointreasuries.org#224]
- [ ] Name: 21Shares AG 
- [ ] Total BTC: 7,769.37497156
- [ ] Product Breakdown: 
ABTC	5632.77471853
ABBA	393.77271402
KEYS	284.96059637
MOON	315.30457870
HODL	1142.56236394

**Comment by nvk** [comment]
Thanks!
