### ISSUE TITLE
Another Site to Crosscheck BTC Ownership

### ISSUE THREAD

**Issue by jey6941** [nvk/bitcointreasuries.org#225]
I recommend using the below website to crosscheck BTC ownership.  It is similar to bitcointreasuries.org and has valuable references.  (https://www.kevinrooke.com/bitcoin)

This other website should give us a more accurate accounting of who and how much.  As of now, it can account for 8.371% of BTC ownership, which is greater than what we have here (~6.54%).

Thanks!

**Comment by nvk** [comment]
Thanks, nice link. Its using different specs :)

**Comment by jey6941** [comment]
Mos def :-)
