### ISSUE TITLE
Total value is BTC 22,373,220

### ISSUE THREAD

**Issue by martijnw** [nvk/bitcointreasuries.org#227]
I think there is a decimal problem here? The total number of BTC is 22373 and some sats, not 22 million? There can never be more than 21 million BTC. Ideally, just drop the decimal separator as it causes errors like this. You can fix this using Format - Number in your Google Sheet.

Furthermore, I would like to thank you for creating this resource. The list has grown quite a lot over the past year or so!

**Comment by nvk** [comment]
The number is correct https://twitter.com/btctreasuries/status/1377405715522977792?s=21

**Comment by martijnw** [comment]
The number on the site, not Twitter is: 22,373,239 

It is on the last row of the table: 
BitcoinTreasuries.org by @NVK.	$57,479,214,913	$1,313,564,170,697	22.9⨉	₿ 22,373,239	106.54%

Look at the decimals, 22 million bitcoin? Number is not correct. :) There will never be more than 21 million Bitcoin. 

Berkshire Hathaway is listed as the first entry with: ₿ 21,000,000 I think that is where the error is? If they own all the BTC, then what are the BTC in my wallet?

--

**Comment by nvk** [comment]
That’s very correct. 😉
