### ISSUE TITLE
MARATHON DIGITAL HOLDINGS ANNOUNCES BITCOIN PRODUCTION AND MINING OPERATION UPDATES FOR THE FIRST QUARTER OF 2021

### ISSUE THREAD

**Issue by Ntanistas** [nvk/bitcointreasuries.org#230]
- [ ] Name: Marathon Digital Holdings
- [ ] Exchange: symbol (NASDA:MARA) 
- [ ] https://www.marathondh.com/news/press-releases/detail/1234/marathon-digital-holdings-announces-bitcoin-production-and
- [ ] Bitcoin Purchase Basis price: $XXX USD
- [ ] Market Cap: $5.54B USD
- [ ] Total BTC: 5,134.2  BTC
- [ ] Direct link to latest financial report: https://www.marathondh.com/news/press-releases/detail/1234/marathon-digital-holdings-announces-bitcoin-production-and

**Please review existing <a href="https://github.com/nvk/bitcointreasuries.org/issues?q=is%3Aissue+is%3Aclosed">closed</a> and open issues before creating a new submission, don't submit just an article without any other information.**

**Comment by nvk** [comment]
updated to my calculated numbers, the article total looks off. Any idea on the basis cost of the recent farming/acquisition?
