### ISSUE TITLE
New section "Companies offering compensation in Bitcoin"

### ISSUE THREAD

**Issue by nvk** [nvk/bitcointreasuries.org#231]
- Start adding here to populate https://bitcointreasuries.org/pays-bitcoin
- Once we have some, we can add a nav menu.

**Comment by torkelrogstad** [comment]
[Arcane Crypto](https://www.arcane.no/) offers salaries in BTC. Blog post about this, from Kaupang Krypto (a subsidiary of Arcane): https://www.kaupangkrypto.no/blogg/lonn-i-bitcoin/

**Comment by nvk** [comment]
live

**Comment by torkelrogstad** [comment]
Thanks, great. A few corrections should be made: 

Hires: Worldwide
Ticker: ARCANE http://www.nasdaqomxnordic.com/shares/microsite?Instrument=SSE67911
Compensation type: salary
Market cap: $260M USD, this obvs varies a bit
