### ISSUE TITLE
HIVE just announced updated holdings of 320 BTC

### ISSUE THREAD

**Issue by nachoguru** [nvk/bitcointreasuries.org#232]
Just saw this in my inbox, quite the jump for them:

https://www.hiveblockchain.com/news/hive-announces-fiscal-year-end-hodl-coin-assets/

> As previously announced since the beginning of the calendar year 2021 HIVE has been a Holder of all mined Bitcoin and Ethereum coins and has been banking them in cold wallets.  As at the completion of our most recently completed fiscal year ended March 31, 2021 we held over 320 Bitcoin and over 20,030 Ethereum coins.
 
> The dollar value of our crypto assets at fiscal year end was approximately US $60 million and cash was US $36 million.

**Comment by nvk** [comment]
thx, updated!
