### ISSUE TITLE
Meitu, Inc. Update

### ISSUE THREAD

**Issue by FracturedWinter** [nvk/bitcointreasuries.org#235]
The Board is pleased to announce that on April 8, 2021, Meitu HK had, pursuant to the Cryptocurrency Investment Plan, further acquired in open market transactions, an additional 175.67798279 units of Bitcoin at an aggregate cash consideration of approximately US$10 million under the Further Bitcoin Acquisition.

Source:
https://www1.hkexnews.hk/listedco/listconews/sehk/2021/0408/2021040802161.pdf

Supporting press coverage:
https://www.theblockcrypto.com/linked/101124/meitu-btc-purchase-100-million-crypto-assets

Previous Issue:
#210

**Comment by nvk** [comment]
updated, thx!
