### ISSUE TITLE
Open Google Sheet to enable the JSON endpoint?

### ISSUE THREAD

**Issue by hoganri** [nvk/bitcointreasuries.org#236]
Possible to enable the permissions on the Google Sheet so that the data/sheet can be used as a JSON endpoint? I'd like to add some visual tools as a new page but need the data access to do it.

[Instructions for the permission changes are available here.](https://www.freecodecamp.org/news/cjn-google-sheets-as-json-endpoint/)

**Comment by nvk** [comment]
tried before, was getting ripped off with no attribution.
