### ISSUE TITLE
NEW: Net Holding

### ISSUE THREAD

**Issue by efecini** [nvk/bitcointreasuries.org#237]
- [ ] Name: Net Holding Anonim Sirketi
- [ ] Exchange: IST: NTHOL
- [ ] https://www.google.com/finance/quote/NTHOL:IST
- [ ] Bitcoin Purchase Basis price: $28,500 USD
- [ ] Market Cap: $2.458 B
- [ ] Total BTC: 2.8 BTC
- [ ] https://t.co/VaegCqgEMt?amp=1

This might be the first Turkish company on BTC Treasuries. Converted the Turkish Lira to USD to find the total amount of BTC holding. The financial report is in Turkish but you can search "bitcoin" in the doc and use Google translate for proof. As a Turkish bitcoiner, I read it all.

**Comment by nvk** [comment]
trying something new, try populating this https://github.com/nvk/bitcointreasuries.org/issues/238

**Comment by efecini** [comment]
Ok but I can't edit it. Give me permission maybe? (efecini@gmail.com)

**Comment by nvk** [comment]
try now, will work

**Comment by nvk** [comment]
on live site now :)

**Comment by efecini** [comment]
Whyis it red tho?  🤔
![Uploading Ekran Resmi 2021-04-11 18.22.00.png…]()

**Comment by nvk** [comment]
thats bad cache, looks gree.
