### ISSUE TITLE
Neptune Dash Technologies Update

### ISSUE THREAD

**Issue by slashiiii** [nvk/bitcointreasuries.org#239]
Market Cap is 78.86m CAD / 62.81 USD

$4,896,343 in BTC are 8% of Market Cap

https://stocktwits.com/symbol/NPPTF

The Company are now mining BTC. BTC increasing will be coming <3

https://neptunedigitalassets.com/neptune-digital-assets-to-receive-its-first-order-of-bitcoin-mining-machines-and-to-complete-private-placement/

**Comment by slashiiii** [comment]
And they changed the Name...Neptune Dash Technologies

TSXV:DASH

**Comment by nvk** [comment]
name change done.
