### ISSUE TITLE
Adding "marketcap" and deriving "exposure %" as "Today's Value"/"marketcap"

### ISSUE THREAD

**Issue by champbronc2** [nvk/bitcointreasuries.org#24]
Just requires adding the following column in Google sheets `=GOOGLEFINANCE("TCKR","marketcap")`

This makes it easy to see the level of conviction or exposure

**Comment by nvk** [comment]
I tried that before, but google finance doesn't seem to have lots of the non US exchanges like CSE.

**Comment by champbronc2** [comment]
Some of the Googlefinance exchange definitions are different https://www.google.co.uk/googlefinance/disclaimer/ but good point that some of these just don't exist on Google Finance at all (BTCE and COINXBT from what I can tell)

For your convenience:
```
=GOOGLEFINANCE("TSE:HUT","marketcap")
=GOOGLEFINANCE("ASX:DCC","marketcap")
=GOOGLEFINANCE("LON:ARB","marketcap")
```

Since the two missing are trackers, maybe it's not necessary to display? For consistency, could treat GBTC and QBTC.U the same.

**Comment by nvk** [comment]
Worked it out, live. Thx!
