### ISSUE TITLE
Cypherpunk Holdings (HODL) just stacked 68.16 more BTC 

### ISSUE THREAD

**Issue by nachoguru** [nvk/bitcointreasuries.org#241]
https://ceo.ca/@newsfile/cypherpunk-holdings-acquires-additional-bitcoins

> Toronto, Ontario--(Newsfile Corp. - April 13, 2021) - Cypherpunk Holdings Inc. (CSE: HODL) (OTC Pink: KHRIF) (the "Company"), a sector leader for privacy-technology investments, is pleased to announce that it has purchased 68.16 bitcoins for an aggregate purchase price of approximately $5 million (Canadian dollars), inclusive of fees and expenses. The average price per bitcoin was $58,092. As a result of this acquisition, the Company now holds an aggregate of 350 bitcoins.

This news release is only about 12 minutes old, so it's not on their corporate news page yet at https://cypherpunkholdings.com/press/ but might be by the time you read this. 

I'll post other links for confirmation as I find them.

**Comment by nvk** [comment]
updated, thx!

**Comment by nachoguru** [comment]
Slight adjustment, I guess you (like I) added 68.16 to their last known # and got 360 -- but the co states their total at the end of that paragraph above at **350 BTC**, not 360 BTC, so I imagine you should use that figure.

They are a fund that invests in privacy tech so I can only imagine they have put that "missing" 10 BTC to good work in some other yet-to-be-announced investment.

(I finally came back to post another link from the news agency for corroboration -- https://www.newsfilecorp.com/release/80292 -- and wow you're fast!)

**Comment by nachoguru** [comment]
Then again a year-old account on CEO.ca with the name of one of the HODL board members posted today:

> yes, 350 btc was a typo unfortunately. Correct balance is 360 btc as of today.

- https://ceo.ca/hodl?2a4c8ef66dcf

...and then they link back to your site in the next post after that like you/we know what we're doing. :)

Not exactly signed with a crypto key but until the company clarifies, this does make sense as why else do the exact .16 other than to get to the nice round total. 

I'll ask them to release something more official to clarify.

Up to you of course, but I guess no need to edit until clarification?
