### ISSUE TITLE
Phunware, Inc. purchases bitcoin

### ISSUE THREAD

**Issue by mchan-phun** [nvk/bitcointreasuries.org#246]
- [ ] Name: Phunware, Inc.
- [ ] Exchange: symbol (NASDA:PHUN)
- [ ] https://www.google.com/finance/quote/PHUN:NASDAQ
- [ ] Bitcoin Purchase Basis price: $58,133 USD
- [ ] Market Cap: $101M USD
- [ ] Total BTC: 25.8 BTC
- [ ] https://investors.phunware.com/sec-filings

Please add Phunware to the list.  Detail of our bitcoin purchase can be found here:
https://investors.phunware.com/news-events/press-releases/detail/178/phunware-board-authorizes-bitcoin-purchases-for-blockchain

**Comment by nvk** [comment]
added
