### ISSUE TITLE
Galaxy Digital Holdings BTC Change??

### ISSUE THREAD

**Issue by Fuelrod2** [nvk/bitcointreasuries.org#247]
Up until just a few weeks ago your site reported Galaxy Digital Holdings had 16,402 BTC, now it says 4,000 BTC.  From all my research I don't see where Galaxy Digital Holdings got rid of any of their BTC.  Is there a reason you dropped the amount of BTC they hold?

**Comment by nvk** [comment]
Corporate structure. The real holdings under this co is what's listed.
