### ISSUE TITLE
HUT8 Mining UPDATED BITCOIN HOLDINGS = 3233

### ISSUE THREAD

**Issue by sevy70** [nvk/bitcointreasuries.org#248]
Hut8 Mining has updated their current bitcoin holdings to 3233 as of March 24, 2021 as per their investor presentation and Twitter. Not yet reflected on bitcoin treasuries

**Comment by nvk** [comment]
Do we have basis cost?

**Comment by sevy70** [comment]
> Do we have basis cost?

Their current cost per coin (all operating and energy expenses included) was 14195 $CAD or 11378 $USD. This would be applicable to the additional 221 bitcoin mined since their last reporting of 3012.

**Comment by nvk** [comment]
Thanks! Updated
