### ISSUE TITLE
Bitfarms (BITF/BFARF) BTC inventory update

### ISSUE THREAD

**Issue by UltimateJatt** [nvk/bitcointreasuries.org#249]
Bitcoin inventory increased to 650.
Average cost is $7,000 USD

https://bitfarms.com/app/uploads/2021/04/2021-04-16__PR-FINAL.pdf
https://thedeepdive.ca/bitfarms-grows-hashrate-to-1-3-eh-s-with-latest-purchase/

**Comment by nvk** [comment]
updated. thx

**Comment by UltimateJatt** [comment]
Total inventory is 650.  Entered incorrectly.

Thanks

**Comment by nvk** [comment]
Fixed
