### ISSUE TITLE
CleanSpark (CLSK)

### ISSUE THREAD

**Issue by UltimateJatt** [nvk/bitcointreasuries.org#250]
- [ ] Name: CleanSpark Inc
- [ ] Exchange: CLSK (NASDA:CLSK) 
- [ ] https://www.google.com/search?q=clsk+stock+price&rlz=1C1GCEV_enCA878CA881&oq=clsk&aqs=chrome.0.69i59j69i57j0i20i131i263i433j0i67l4j0l3.2452j0j7&sourceid=chrome&ie=UTF-8
- [ ] Bitcoin Purchase Basis price: $N/A USD
- [ ] Market Cap: $735,000,000 USD
- [ ] Total BTC: 143 BTC
- [ ] https://www.cleanspark.com/investor-relations/news-releases/

**Comment by nvk** [comment]
Added, Thanks!
