### ISSUE TITLE
New Zealand’s KiwiSaver Fund Enters Bitcoin Market

### ISSUE THREAD

**Issue by SteveGoAllBlacks** [nvk/bitcointreasuries.org#251]
Hey, team:

Thanks for your awesome job. Just a headsup that our retired fund investing in Bitcoion as well. Not sure if you have that on your list but just a quick feedback. See the link below. 

https://www.financemagnates.com/cryptocurrency/news/new-zealands-kiwisaver-fund-enters-bitcoin-market/

Again, thanks for the great website.

**Comment by nvk** [comment]
Please see template.
