### ISSUE TITLE
Nexon Joins Tesla in Bitcoin Bet With $100 Million Purchase from Bloomberg today

### ISSUE THREAD

**Issue by SteveGoAllBlacks** [nvk/bitcointreasuries.org#252]
https://www.bloomberg.com/news/articles/2021-04-28/nexon-joins-tesla-in-bitcoin-bet-with-100-million-purchase

**Comment by nvk** [comment]
pay wall

**Comment by nvk** [comment]
Please see template format for additions

**Comment by SteveGoAllBlacks** [comment]
Sorry, I am a newbie here. Can you tell me where to find the template? Thx.

**Comment by nvk** [comment]
no worries, already added! 

Yes, either add to this template  https://docs.google.com/spreadsheets/d/1TqL5qW5rLeEDBhOQk3RwtaJbHA8ExkfsAjJQ4lzCLA8/edit#gid=0

or this as an issue here: 

- [ ] Name: Coin Citadel OTC
- [ ] Exchange: symbol (NASDA:SQ) or wherever I can find it
- [ ] Link to google finance or wherever I can find it
- [ ] Bitcoin Purchase Basis price: $XXX USD
- [ ] Market Cap: $XXX USD
- [ ] Total BTC: XXX BTC
- [ ] Direct link to latest financial report

**Please review existing <a href="https://github.com/nvk/bitcointreasuries.org/issues?q=is%3Aissue+is%3Aclosed">closed</a> and open issues before creating a new submission, don't submit just an article without any other information.**

**Comment by nvk** [comment]
You can also see previous entries here https://github.com/nvk/bitcointreasuries.org/issues?q=is%3Aissue+is%3Aclosed
