### ISSUE TITLE
Q1 earnings show Tesla sold off $272 million of its BTC purchase

### ISSUE THREAD

**Issue by SteveGoAllBlacks** [nvk/bitcointreasuries.org#253]
https://www.theblockcrypto.com/linked/102899/q1-earnings-show-tesla-sold-off-272m-of-its-btc-purchase

**Comment by nvk** [comment]
Not clear what exact number they sold yet, so not updating till we have real numbers.

**Comment by SteveGoAllBlacks** [comment]
The sale trimmed Tesla’s position by 10%, Tesla CFO Zach Kirkhorn said on an earnings call Monday. 

It is in Yahoo Finance. 

https://finance.yahoo.com/news/tesla-sold-bitcoin-q1-proceeds-202359810.html?guccounter=1&guce_referrer=aHR0cHM6Ly93d3cuZ29vZ2xlLmNvbS8&guce_referrer_sig=AQAAAK17PVsFfxv7mJrmid7z7soGrD83FQebyN0DtpecpNX09joLO7BP0r0RXtfNnVFm5PsXghQkvsQgZtu50S42fYpWz1WqkNt8VpxUeZCik6a10fsQsvhOoGi59Bia6K4XPx2KopAPQS3wJJpSLnbqMqxht74E6mqVkw2R4XO4OOgf

**Comment by nvk** [comment]
thx, updated.

**Comment by mutatrum** [comment]
Looks like something went wrong with updating this, it now says current value for Tesla is $234MM.

**Comment by nvk** [comment]
fixed
