### ISSUE TITLE
% BTC of Nexon Co. Ltd is off

### ISSUE THREAD

**Issue by jgmontoya** [nvk/bitcointreasuries.org#254]
Current market cap of Nexon is: 3,207,728,815,790 YEN which is roughly $29,468,852,901.31 (source: https://quote.jpx.co.jp/jpx/template/quote.cgi?F=tmp/e_stock_detail&MKTN=T&QCODE=3659)

This makes for a % BTC of ~0.34% [(100m / 29,468m) * 100]%

**Comment by nvk** [comment]
Can't use it because it wont live update without being available on GF api.

**Comment by jgmontoya** [comment]
Right, but at least we could leave a better hard-coded value on the `% BTC` field. It currently shows 80% which is way off.
