### ISSUE TITLE
Ukraine listing is misleading

### ISSUE THREAD

**Issue by torkelrogstad** [nvk/bitcointreasuries.org#256]
The current listing of "Gov | Ukraine (various)" is misleading IMO. The linked report refers to individuals who happen to be elected officials holding bitcoin privately, not the government holding bitcoin. Currently, the table gives the impression that the government of Ukraine holds BTC.

**Comment by nvk** [comment]
will be tweaked in the future

**Comment by crc32** [comment]
Given that Ukraine is now in the news, this entry should be updated to avoid incorrect reporting using this site as a source.
