### ISSUE TITLE
Update Neptune Digital

### ISSUE THREAD

**Issue by slashiiii** [nvk/bitcointreasuries.org#257]
New BTC Amount...

91 instead of 82

Earnings:
https://www.streetinsider.com/Newsfile/Neptune+Commences+Bitcoin+Mining+Operations+and+Provides+Corporate+Update/18321030.html

**Please review existing <a href="https://github.com/nvk/bitcointreasuries.org/issues?q=is%3Aissue+is%3Aclosed">closed</a> and open issues before creating a new submission, don't submit just an article without any other information.**

**Comment by nvk** [comment]
updated, thx!

**Comment by samysousa** [comment]
Opened a new one to update Ticker and other Info.
But BTC holdings have not changed
