### ISSUE TITLE
Removing MTGOX

### ISSUE THREAD

**Issue by lewww1** [nvk/bitcointreasuries.org#261]
MTGOX "treasury" is in reality deposits owed to customers (these coins are not assets but in fact a liability that is underfunded). They don't belong to them or have a claim on these assets.

Following this logic, the Coinbase "treasury" should reflect all customer deposits but this would lead to double-counting treasuries (since customers on the list custody with them) and in a way, ruin the data since it's not their actual treasury.

To keep the list pure, I would suggest removing Gox and keeping companies that own the rights to the bitcoin. Even if purchases are funded with debt (ex: MSTR), the company owes $ to the lender, not BTC.

**Comment by nvk** [comment]
Please search precious issues

**Comment by lewww1** [comment]
I did - I don't think it should be on the list regardless of whether the trust has or hasn't refunded the funds to customers. The coins held by the trustee is not a treasury asset, wouldn't you agree?
