### ISSUE TITLE
Update Marathon Digital Holdings Bitcoin holdings - 5,292 BTC

### ISSUE THREAD

**Issue by ramiy** [nvk/bitcointreasuries.org#262]
- [*] Name: Marathon Digital Holdings, Inc.
- [*] Exchange: symbol (NASDA:MARA)
- [*] Total BTC: **5,292 BTC**
- [*] Direct link to the source - https://finance.yahoo.com/news/marathon-digital-holdings-announces-bitcoin-200000569.html

**Comment by nvk** [comment]
Do we know the cost of mining those?

**Comment by nvk** [comment]
btw, yahoo finance math does add to mine =5066.66+196+162.1
