### ISSUE TITLE
Add West Coast Aquaculture Group Ltd (WCA) listed on SSX (Sydney Stock Exchange) in Australia

### ISSUE THREAD

**Issue by Pras-Zerocap** [nvk/bitcointreasuries.org#265]
- [ ] Name: West Coast Aquaculture Group Ltd (WCA)
- [ ] Exchange: (SSX Code: 833)
- [ ] Link: https://www.bloomberg.com/quote/833:AU
- [ ] Bitcoin Purchase Basis price: 3,445,070 USDT at IPO
- [ ] Market Cap: $10M USD
- [ ] Total BTC: held 3,445,070 USDT at IPO
- [ ] Direct link to latest financial report: https://www.ssx.sydney/en/investors/securities/security-price/?listeecode=833

**Comment by nvk** [comment]
I can't find the qty of btc
