### ISSUE TITLE
Add Bulgarian government (seized 213k bitcoin years ago)

### ISSUE THREAD

**Issue by btc-steed** [nvk/bitcointreasuries.org#267]
https://www.coindesk.com/bulgarian-government-sitting-3-billion-bitcoin

https://bivol.bg/mvr-zdoi-bitcoins.html

**Comment by nvk** [comment]
added

**Comment by anthonyyaco** [comment]
This seems to be outdated, Bulgaria did not HODL
Same website Coindesk links in their article about the gov response, followed up in April 2018 to say they sold it.
https://bivol.bg/bg-bitcoin-deal.html

"We are buying a new squadron for the Air Force"
"The deal was concluded secretly at the most profitable moment at the end of December 2017 and brought BGN 6 billion to the budget, which means that we took EUR 15,000 for one bitcoin."
https://translate.google.com/translate?hl=&sl=auto&tl=en&u=https%3A%2F%2Fbivol.bg%2Fbg-bitcoin-deal.html
