### ISSUE TITLE
Add: 3iQ CoinShares Bitcoin ETF

### ISSUE THREAD

**Issue by CALoewen** [nvk/bitcointreasuries.org#268]
- [ ] Name: 3iQ CoinShares Bitcoin ETF
- [ ] Exchange: (TSX:BTCQ, BTCQ.U)
- [ ] https://money.tmx.com/en/quote/BTCQ
- [ ] Bitcoin Purchase Basis price: $56,101 USD
- [ ] Market Cap: $1,033,865,286.58 USD
- [ ] Total BTC: 18,242 BTC
- [ ] Direct link to latest financial report: https://3iq.ca/3iq-bitcoin-etf-btcq/

**Please review existing <a href="https://github.com/nvk/bitcointreasuries.org/issues?q=is%3Aissue+is%3Aclosed">closed</a> and open issues before creating a new submission, don't submit just an article without any other information.**

**Comment by nvk** [comment]
do they still have the old product or did they convert into an ETF?

**Comment by nvk** [comment]
aded
