### ISSUE TITLE
Update Neptune Digital Assets - New Ticker is TSX-V:NDA  (NDA.V) - Previously Neptune Dash Technologies

### ISSUE THREAD

**Issue by samysousa** [nvk/bitcointreasuries.org#269]
- [ ] Name: Neptune Digital Assets
- [ ] Exchange: TSX-V:NDA   or NDA:CVE
- [ ] https://www.google.com/finance/quote/NDA:CVE
- [ ] Bitcoin Purchase Basis price: Unknown
- [ ] Market Cap: Unchanged
- [ ] Total BTC: 91 BTC - Unchanged
- [ ] https://neptunedigitalassets.com/financials/2021-28-Feb-FS.pdf

Previously known and on the list as "**Neptune Dash Technologies**"

Changed Ticker on Feb 12 2021 :
https://neptunedigitalassets.com/neptune-digital-announces-symbol-change-date-and-corporate-update/

Latest News shows Unchanged BTC holdings 
https://neptunedigitalassets.com/neptune-commences-bitcoin-mining-operations-and-provides-corporate-update/

**Please review existing <a href="https://github.com/nvk/bitcointreasuries.org/issues?q=is%3Aissue+is%3Aclosed">closed</a> and open issues before creating a new submission, don't submit just an article without any other information.**

**Comment by nvk** [comment]
updated thx
