### ISSUE TITLE
New [Brooker Group's]

### ISSUE THREAD

**Issue by pete2530** [nvk/bitcointreasuries.org#270]
- [ ] Name: Brooker Group's
- [ ] Exchange: SET:BROOK
- [ ] https://www.google.com/finance/quote/BROOK:BKK?sa=X&ved=2ahUKEwjDuvS7jNDwAhXy4nMBHWR9BBwQ_AUoAXoECAEQAw
- [ ] Bitcoin Purchase Basis price: $53,958 USD
- [ ] Market Cap: $256,000,000 USD
- [ ] Total BTC: 122.3158 BTC
- [ ] https://www.set.or.th/set/newsdetails.do?newsId=16207755545930&language=en&country=US

**Please review existing <a href="https://github.com/nvk/bitcointreasuries.org/issues?q=is%3Aissue+is%3Aclosed">closed</a> and open issues before creating a new submission, don't submit just an article without any other information.**

**Comment by nvk** [comment]
added thx!
