### ISSUE TITLE
Mercadolibre buy

### ISSUE THREAD

**Issue by carl0sfelipe** [nvk/bitcointreasuries.org#272]
- [ ] Name: Coin Citadel OTC
- [https://www.google.com/amp/s/www.coindesk.com/e-commerce-giant-mercadolibre-discloses-7-8m-bitcoin-buy%3famp=1 ] Exchange: symbol (NASDA:MELI) or wherever I can find it
- [ https://www.google.com/amp/s/www.coindesk.com/e-commerce-giant-mercadolibre-discloses-7-8m-bitcoin-buy%3famp=1] Link to google finance or wherever I can find it
- [ 7.8 M] Bitcoin Purchase Basis price: $XXX USD
- [ 30Bi] Market Cap: $XXX USD
- [ ] Total BTC: XXX BTC
- [ ] Direct link to latest financial report

**Please review existing <a href="https://github.com/nvk/bitcointreasuries.org/issues?q=is%3Aissue+is%3Aclosed">closed</a> and open issues before creating a new submission, don't submit just an article without any other information.**

**Comment by nvk** [comment]
please see other issues.
