### ISSUE TITLE
Bitfarms - Q1 2021 Update

### ISSUE THREAD

**Issue by DaniloWalter** [nvk/bitcointreasuries.org#275]
CSE:BITF
- [x] Total BTC: 1000 BTC is the right number. Not 650. Thanks!

Bitfarms Limited | CA | CSE:BITF | $882,163,555 | 2.9% | Ann | ? $16,817,350 | $26,017,290 | 1.5⨉ | **₿ 650** | .003%
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --

BITFARMS Q1 2021

Q1 2021 Results Presentation
bit.ly/BQ12021RP

Q1 2021 News Release
bit.ly/BQ12021NR

Q1 2021 Financial Statements
bit.ly/BQ12021FS

Q1 2021 Management’s Discussion & Analysis
bit.ly/BQ12021MDA

**Comment by nvk** [comment]
updated
