### ISSUE TITLE
Hut 8 Mining - update 2021-Q1 report

### ISSUE THREAD

**Issue by jzaluski** [nvk/bitcointreasuries.org#276]
- [ ] Total BTC: 3,522
- [ ] 2021-Q1 https://hut8mining.com/wp-content/uploads/2021/05/Hut-8-FS-Q1-2021-v8-2021-05-12-FINAL.pdf

https://twitter.com/Hut8Mining/status/1392820225012342784

**Comment by nvk** [comment]
updated
