### ISSUE TITLE
Update on 3iq bitcoin fund, Purpose, ETC bitcoin group

### ISSUE THREAD

**Issue by marcodiomede** [nvk/bitcointreasuries.org#277]
3iq Bitcoin Fund TSX:QBTC.U 23459 BTC
https://3iq.ca/the-bitcoin-fund/

ETC bitcoin Group ETP BTCE:GR 17421
https://etc-group.com/it/products/btcetc/

Purpose Bitcoin ETF - BTCC they have 19161 BTC
https://www.purposeinvest.com/funds/purpose-bitcoin-etf

**Comment by nvk** [comment]
updated, thanks
