### ISSUE TITLE
Make a new site like BitcoinCountries.net

### ISSUE THREAD

**Issue by ViktorBohu** [nvk/bitcointreasuries.org#281]
Should be a nice addition to companies, jobs & athletes. Basically a Worldmap with every country being white for now (doesn't use Bitcoin).

Green countries = uses Bitcoin / official currency (El Salvador)
Orange countries = plans to use Bitcoin (Paraguay)
Yellow countries = HODLs Bitcoin

**Comment by ViktorBohu** [comment]
I know the Domain / base site already exists but I think a World Map with nice colors would be a better visualisation for countries instead of a table

**Comment by nvk** [comment]
started simple https://bitcointreasuries.net/countries
