### ISSUE TITLE
LQwD FinTech Corp

### ISSUE THREAD

**Issue by 0xfff** [nvk/bitcointreasuries.org#285]
- [LQwD FinTech Corp ] Name: Coin Citadel OTC
- [ TSXV: LQWD] Exchange: symbol (NASDA:SQ) or wherever I can find it
- [ https://www.google.com/finance/quote/LQWD:CVE] Link to google finance or wherever I can find it
- [$38,000 ] Bitcoin Purchase Basis price: $XXX USD
- [ 50,000,000] Market Cap: $XXX USD
- [ 60] Total BTC: XXX BTC
- [ https://www.newswire.ca/news-releases/lqwd-announces-acquisition-of-bitcoins-to-fuel-lightning-network-operations-833855807.html] Direct link to latest financial report

**Please review existing <a href="https://github.com/nvk/bitcointreasuries.org/issues?q=is%3Aissue+is%3Aclosed">closed</a> and open issues before creating a new submission, don't submit just an article without any other information.**

**Comment by nvk** [comment]
thx, added!

**Comment by 0xfff** [comment]
on the webpage there is an `L` missing in the name
<img width="1051" alt="bitcoint net" src="https://user-images.githubusercontent.com/4933679/122469027-4fae2900-cf71-11eb-955c-84398f3b0292.png">
