### ISSUE TITLE
Make the "Company Name" column wider.

### ISSUE THREAD

**Issue by efecini** [nvk/bitcointreasuries.org#30]
<img width="1093" alt="Ekran Resmi 2020-10-13 00 48 07" src="https://user-images.githubusercontent.com/3943422/95793312-f5780c80-0ced-11eb-8fac-943a9d13b320.png">

**Comment by nvk** [comment]
The report shows the longer name. What’s the official name on the records?

**Comment by nvk** [comment]
Sorry, mixed. I can't make it wider atm, its not mobile friendly os trying to keep as short as possible.
