### ISSUE TITLE
Find reports to add Stone Ridge Asset Management/NYDIG

### ISSUE THREAD

**Issue by nvk** [nvk/bitcointreasuries.org#33]
10K btc https://www.forbes.com/sites/michaeldelcastillo/2020/10/13/stone-ridge-reveals-115-million-bitcoin-investment-as-part-of-billion-dollar-spin-off/#658c94619850

**Comment by nvk** [comment]
Alex is on this.

**Comment by TharaGTP** [comment]
https://www.stoneridgefunds.com/

**Comment by nvk** [comment]
Added. live.
