### ISSUE TITLE
Adding *Large Private Companies* section. 

### ISSUE THREAD

**Issue by nvk** [nvk/bitcointreasuries.org#34]
- Needs to be 50M+ in bitcoin held to qualify.
- Some notoriety so that is easier to validate the data.

**Comment by jmcorgan** [comment]
ACK

**Comment by nvk** [comment]
https://bitcointreasuries.org/add live

**Comment by nvk** [comment]
Central Bank application section also added https://bitcointreasuries.org/add

:P

**Comment by thehapax** [comment]
> Central Bank application section also added https://bitcointreasuries.org/add
> 
> :P

Absolutely ACK!

Perhaps, since the St Louis Fed loves bitcoin so much, one day we'll find out there is a secret stash.
