### ISSUE TITLE
Exodus Movement, Inc.

### ISSUE THREAD

**Issue by colinclosser** [nvk/bitcointreasuries.org#340]
Exodus Movement, Inc. ($EXOD)

1) tZERO: EXOD, Securitize Markets: EXOD
2) 1-K filing: https://www.sec.gov/Archives/edgar/data/1821534/000114036122008049/brhc10034275-1kv13.htm
3) **1,322 BTC** held in treasury **Found on page F-21 of above SEC link**
4) Purchase price (Book value): **$33,253,000 USD** **Found on page F-21 of above SEC link**

**Comment by nvk** [comment]
Come add it on the new site bitcointreasuries.net/login
