### ISSUE TITLE
Add MSE: BUN

### ISSUE THREAD

**Issue by AbsoluteOREO** [nvk/bitcointreasuries.org#341]
- [x] Name: Crypto Nation JSC
- [x] Exchange: symbol (MSE:BUN)
- [x] Link (https://www.mse.mn/en/company/308)
- [x] Bitcoin Purchase Basis price: $12,000 USD
- [x] Market Cap: $2,161,875.84 USD
- [x] Total BTC: 8.39 BTC
- [x] Total ETH: 72.45 ETH
- [x] [Direct link to latest financial report](https://www.mse.mn/issuers/activityreport/308_20220720104913report.pdf)

**Please review existing <a href="https://github.com/nvk/bitcointreasuries.org/issues?q=is%3Aissue+is%3Aclosed">closed</a> and open issues before creating a new submission, don't submit just an article without any other information.**

**Comment by nvk** [comment]
Come add it on the new site bitcointreasuries.net/login
