### ISSUE TITLE
submit a new public company - Coin Citadel OTC (CCTL)

### ISSUE THREAD

**Issue by coincitadel** [nvk/bitcointreasuries.org#35]
Coin Citadel OTC (CCTL)
Coin Citadel invested in Bitcoin back in 2014.
https://webcache.googleusercontent.com/search?q=cache:nj-MMwZKkVQJ:https://insiderfinancial.com/coin-citadel-com-npv-otcmktscctl-is-a-top-bitcoin-play/123612/+&cd=1&hl=en&ct=clnk&gl=us
www.coincitadel.net 
Financials posted on web site
email ir@coincitadel.net
Coin Citadel was one of the earliest public traded companies to invest in Bitcoin, if not the first.

**Comment by nvk** [comment]
- Want to submit a new public company?
- MUST be publicly traded, please include symbol and exchange (ie NASDAQ:SQ)
- MUST include filing or announcement link
- MUST include total BTC held in Treasuries
- MUST include purchase price and/or total in the balance sheet as of last filing in USD
- IF you have ALL those items create an issue here

**Comment by coincitadel** [comment]
LINK to OTC Filed annual report 2015 
https://backend.otcmarkets.com/otcapi/company/financial-report/151105/content

**Comment by nvk** [comment]
>Coin Citadel was one of the earliest public traded companies to invest in Bitcoin, if not the first.
Neat 👍 

---

Could reply below with the summary in this format to clarify:

name: Coin Citadel OTC 
exchange:symbol (OTCX:CCTL) or wherever I can find it
Basis price: $XXX
Market Cap: $XXX
Total BTC: XXX BTC

**Comment by coincitadel** [comment]
Name: Coin Citadel Inc
Exchange: OTCMKTS: CCTL
Basic price: BTC $359.43 or $184,389.59 (BTC price Sept 29, 2014)
Market Cap: $3,361,343.00
Total BTC: 513 BTC

https://www.otcmarkets.com/stock/CCTL/profile

Thomas W Pillsworth
CEO Coin Citadel
www.coincitadel.net
ph: 212-292-7460

**Comment by nvk** [comment]
live https://twitter.com/nvk/status/1316405429463846915?s=20

**Comment by coincitadel** [comment]
Yes. Cap figure is correct at current stock price $3,361,343 (yet should not be in reality)
We were at $5m 3 weeks ago but stock has price has retracted since then

We have had short pressure over the past year or so. Someone big is trying to destroy stock value. Still trying to get to the bottom of that.

Between you and me old CEO destroyed the company’s reputation during his tenure.
He was supposed to buy another 1700 BTC on a stock deal, but kept/paid the money to himself in salary. So some hype PR’s released that never panned out destroyed reputation.

I was hired as a consultant to build BTC mining division up here in Plattsburgh NY. The town infamously known to have banned Bitcoin mining for 18 months
Which destroyed our plans to expand mining operation for 2 years.

If you google Tom Pillsworth and Bitcoin I’m in numerous news articles, fron page of business section NY Times Feb 2018, Full Measure news, Vice etc…

Its been a wild ride.

But turning around Company and bringing it current.

Thomas Pillsworth
CEO Coin Citadel
