### ISSUE TITLE
Bitcoin-based financial instruments issuer doesn't mean they hold their treasury in BTC

### ISSUE THREAD

**Issue by lclc** [nvk/bitcointreasuries.org#38]
I'm not a finance guy, but I  think a company that issues Bitcoin certificates, EPTs, ETNs, ETFs etc. is no equal to someone who holds Bitcoin as treasury?

Of course it could be both, a publicly listed company which issues Bitcoin-based financial instruments AND holds it's own treasury in Bitcoin. But for at least one of the list, this is not the case afaik (21Shares AG) - they aren't publicly listed and I don't know about their treasury.

**Comment by nvk** [comment]
This arguments comes by often, please see the fine print at the bottom :)
