### ISSUE TITLE
New company for the list - FRMO Corp.

### ISSUE THREAD

**Issue by FredrikNYC** [nvk/bitcointreasuries.org#39]
FRMO Corp. (FRMO) is publicly traded, with $211 million market cap.
Holds 63 BTC, in addition to some five other cryptocurrencies.
https://www.frmocorp.com/_content/letters/2020.pdf (page 2)

**Comment by nvk** [comment]
Thx. Do you have their Bitcoin purchase price?

**Comment by FredrikNYC** [comment]
These BTC were mined by FRMO, so they were not open market transactions.

**Comment by nvk** [comment]
Added, live now https://twitter.com/nvk/status/1316382766863454209?s=20

If you are familiar with this company and knows the dates they added to the books we could use that as the basis price.
