### ISSUE TITLE
Add BIGG Digital Assets Inc to your list (CSE: BIGG)

### ISSUE THREAD

**Issue by markbinns** [nvk/bitcointreasuries.org#44]
BIGG is public on the CSE. Ticker: BIGG.
BIGG has 145 BTC in inventory, as of Oct 1, 2020.
I am the CEO of BIGG, can vouch for it.

You can see digital holdings, by value, in all SEDAR filings.

Let me know if you have any questions. Would like to be added to your list.
mark@biggdigitalassets.com

**Comment by nvk** [comment]
See template https://github.com/nvk/bitcointreasuries.org/issues/43

**Comment by nvk** [comment]
Please re-submit with this template:

 Name: Coin Citadel OTC
 Exchange:symbol (NASDA:SQ) or wherever I can find it
 Link to google finance or wherever I can find it
 Basis price: $XXX
 Market Cap: $XXX
 Total BTC: XXX BTC
 Direct link to latest financial report

**Comment by markbinns** [comment]
> Name: BIGG Digital Assets Inc.
> Exchange:symbol (CSE:BIGG) 
> 
> 
https://www.google.ca/search?q=CNSX:+BIGG&stick=H4sIAAAAAAAAAONgecRowS3w8sc9YSn9SWtOXmPU5OIKzsgvd80rySypFJLmYoOyBKX4uXj10_UNDZPNCkvKjbIseAADVJ9RPQAAAA&tbm=fin&hl=en&gl=ca#scso=_BHeIX9KXHoXL-gTtnKSgAg7:0 <https://www.google.ca/search?q=CNSX:+BIGG&stick=H4sIAAAAAAAAAONgecRowS3w8sc9YSn9SWtOXmPU5OIKzsgvd80rySypFJLmYoOyBKX4uXj10_UNDZPNCkvKjbIseAADVJ9RPQAAAA&tbm=fin&hl=en&gl=ca#scso=_BHeIX9KXHoXL-gTtnKSgAg7:0>


> Basis price: $1.435M CAD (cost basis)
> Market Cap: $2.2M CAD (in BTC value)
> Total BTC: 145 BTC
> 
> 
https://www.sedar.com/DisplayProfile.do?lang=EN&issuerType=03&issuerNo=00036793 <https://www.sedar.com/DisplayProfile.do?lang=EN&issuerType=03&issuerNo=00036793>

>

**Comment by nvk** [comment]
Thanks, could you point me to the filing that shows 145 in BTC? Can't find it.

**Comment by markbinns** [comment]
Look at Notes 4 and 5 in the most recent (Q2 2020) financials on SEDAR.
SEDAR doesn’t let you send a direct link. Here are the notes:
We have the BTC in 2 places, together worth $2.3M CAD in June 30. 2020.
There are 100.94 within Blockchain Intelligence Group and another $1,063,136 in Netcoins.
At the time is was probably around 170 BTC. But today we have 145 BTC.

Hope that helps.

**Comment by nvk** [comment]
its live https://twitter.com/nvk/status/1316883641335775232

**Comment by markbinns** [comment]
Awesome - thank you.

**Comment by markbinns** [comment]
We now have 189.5 BTC.

Can you update our profile?

https://www.globenewswire.com/news-release/2020/12/08/2141282/0/en/BIGG-Digital-Assets-Inc-Purchases-Additional-40-Bitcoins-for-Treasury-Total-Bitcoin-Treasury-Reaches-189-5-BTC.html

Let me know and thanks.

Mark Binns
7786287427
