### ISSUE TITLE
Grayscale BTC new Holding +6937 BTC

### ISSUE THREAD

**Issue by ChakTochi** [nvk/bitcointreasuries.org#45]
Hello,

Grayscale BTC new holding is = 456 537 BTC = 478 480 300 * 0.00095414 = Shares Outstanding * Bitcoin per Share

Source : https://grayscale.co/bitcoin-trust/

**Comment by nvk** [comment]
I would be grateful if you please re-submit with this template:

Name: Coin Citadel OTC
 Exchange:symbol (NASDA:SQ) or wherever I can find it
 Link to google finance or wherever I can find it
 Basis price: $XXX USD
 Market Cap: $XXX USD
 Total BTC: XXX BTC
 Direct link to latest financial report

**Comment by nvk** [comment]
It's hard to keep it up to date, I will remove those type products soon. They are not real hodl.

**Comment by nvk** [comment]
updated
