### ISSUE TITLE
Add Block.One : 140,000 bitcoin on b/s

### ISSUE THREAD

**Issue by francksi** [nvk/bitcointreasuries.org#46]
https://cryptobriefing.com/24-million-sec-penalty-block-one-spent-more-on-a-domain-name
https://www.financemagnates.com/cryptocurrency/news/block-one-to-buyback-shares-with-6567-percent-return/

**Comment by nvk** [comment]
Please re-submit in this template:

 Name: Coin Citadel OTC
  Exchange:symbol (NASDA:SQ) or wherever I can find it
  Link to google finance or wherever I can find it
  Basis price: $XXX
  Market Cap: $XXX
  Total BTC: XXX BTC
  Direct link to latest financial report
