### ISSUE TITLE
Block.one

### ISSUE THREAD

**Issue by francksi** [nvk/bitcointreasuries.org#47]
Name: Block.one
Exchange: n/a it's private
https://www.crunchbase.com/organization/block-one/company_financials
Basis price: n/a
Market Cap: 2.4bn
https://craft.co/block-one/metrics
Total BTC: 140,000 BTC
https://www.reddit.com/r/eos/comments/broxto/blockone_is_an_enormous_bitcoin_holder_at_140000/

**Comment by nvk** [comment]
Please resubmit on this format:

 Name: Coin Citadel OTC
 Exchange:symbol (NASDA:SQ) or wherever I can find it
 Link to google finance or wherever I can find it
 Basis price: $XXX
 Market Cap: $XXX
 Total BTC: XXX BTC
 Direct link to latest financial report

**Comment by nvk** [comment]
Where did you find the Market Cap?

**Comment by nvk** [comment]
Would be great if we got more info, but added. Live now https://twitter.com/nvk/status/1318214246249934848?s=20

**Comment by francksi** [comment]
From https://craft.co/block-one/metrics
