### ISSUE TITLE
Hive Blockchain

### ISSUE THREAD

**Issue by seedrthenewccy** [nvk/bitcointreasuries.org#50]
- [ ] Name: Hive Blockchain
- [ ] Exchange: HVBTF
- [ ] https://www.hiveblockchain.com/
- [ ] Basis price: ???
- [ ] Market Cap: $109,505,000 USD
- [ ] Total BTC: 211.43 BTC
- [ ] https://www.hiveblockchain.com/medias/uploads/HIVEFS_qTAflZC.pdf
- [ ] https://www.hiveblockchain.com/news/hive-blockchain-reports-first-quarter-f2021-financial-results/

**Comment by seedrthenewccy** [comment]
Estimated basis price: $614,724.25 USD

Used Financials from March 31, 2020: https://www.hiveblockchain.com/medias/uploads/HIVEFS_qTAflZC.pdf

Cost of mining (page 2): $20,707,315 USD
Income from mining (page 2): $29,219,843 USD
Company holding of Bitcoin (page19):  $867,430 USD

(20,707,315 / 29,219,843) = 0.7087
 0.7087 * 867,430 = 614,724.25

**Comment by seedrthenewccy** [comment]
Estimated total BTC: 211.43 BTC

Used Financials from March 31, 2020: https://www.hiveblockchain.com/medias/uploads/HIVEFS_qTAflZC.pdf
Used bitcoin price on March 31, 2020 from coinmarketcap.com: $4102.56

Company holding of Bitcoin (page19): $867,430 USD
867,430 / 4102.56 = 211.43

**Comment by nvk** [comment]
Where could I find any numbers that is not the own company's website? ie Google Finance or Bloomberg?

**Comment by nvk** [comment]
live https://twitter.com/nvk/status/1318214246249934848?s=20

**Comment by seedrthenewccy** [comment]
> Where could I find any numbers that is not the own company's website? ie Google Finance or Bloomberg?

Here is the company on Google Finance: 
https://www.google.com/finance/quote/HVBTF:OTCMKTS
