### ISSUE TITLE
The Tezos Foundation

### ISSUE THREAD

**Issue by fwaters22** [nvk/bitcointreasuries.org#51]
- [ ] Name: The Tezos Foundation
- [ ] Exchange: N/A. private foundation based in Switzerland
- [ ] https://www.crunchbase.com/organization/tezos-foundation
- [ ] Basis price: N/A. Raised via ICO in 2017
- [ ] Market Cap: Private Company. 751 million USD in total assets under management as of July 31, 2020
- [ ] Total BTC: 24,808 
- [ ] https://tezos.foundation/reports/

**Comment by nvk** [comment]
Are there any public audited reports, history of ICO entities is not stellar.

**Comment by fwaters22** [comment]
Yes. They release Biannual reports, the most recent in September 2020. https://tezos.foundation/reports/

On page 37 of the most recent report they state they are audited by PriceWaterhouseCooper.

" In June 2020, the third statutory audit by PricewaterhouseCoopers for the 2019 financial year was successfully completed. This time, their scope covered statutory financial statements under local accounting frameworks and consolidated financial statements in accordance with international financial reporting standards (IFRS for SMEs).

The Tezos Foundation is the only large-scale blockchain foundation to be audited by a “Big4” auditor and, as customary and mandated by Swiss law, the audit report has been filed with the Swiss Federal Supervisory Authority for
Foundations. The Tezos Foundation is proud to have been able to achieve its goal to be part of a small group of organizations with significant cryptocurrency holdings that have received unqualified audit reports. "

**Comment by nvk** [comment]
added https://twitter.com/nvk/status/1318544585015087105?s=20
