### ISSUE TITLE
The Bit Digital, Inc.

### ISSUE THREAD

**Issue by 521314** [nvk/bitcointreasuries.org#53]
1. Name:The Bit Digital, Inc.
    NASDAQ:BTBT

2. Announcement link : http://www.bit-digital.com/index.php/press-releases
    Official website : http://www.bit-digital.com/

3. 16 btc on June 30, 2020 and 930 btc on September 30,2020
    (Financial report reference : https://www.sec.gov/Archives/edgar/data/1710350/000121390020031938/ea128462ex99-1_bitdigital.htm)

4. As of the filing date on October 19, 2020, We have earned an aggregation of 949.51 bitcoins and recognized unaudited revenues of approximately $10.08 million. The averaged purchase price is $10.08 Million / 945.51 = $10,616.

Market Capitalization :  $179.16M

**Comment by nvk** [comment]
added https://twitter.com/nvk/status/1318544585015087105?s=20
