### ISSUE TITLE
Add Mode Global Holdings PLC,

### ISSUE THREAD

**Issue by nvk** [nvk/bitcointreasuries.org#55]
- [x] Name: Mode Global Holdings PLC
- [x] LON:MODE
- [x] https://www.google.com/search?tbm=fin&sxsrf=ALeKk02ZR3itMb23cgtY2jCJVuKhDVmy8g%3A1603283674049&ei=2iqQX5K9AsrH_QbTkKXQAg&q=Mode+Global+Holdings+PLC+Mode&oq=Mode+Global+Holdings+PLC+Mode&gs_l=finance-immersive.3..81.12547.12547.0.13131.1.1.0.0.0.0.94.94.1.1.0....0...1c.2.64.finance-immersive..0.1.93....0.qA-UxudNCKw#scso=_5yqQX9SqOYGHggfun66oDQ7:0
- [ ] Basis price: $XXX USD
- [ ] Market Cap: 36.40M
- [ ] Total BTC: XXX BTC
- [ ] Direct link to latest financial report

"(10%) of its cash reserves" no numbers?!?

https://uk.advfn.com/stock-market/london/mode-global-MODE/share-news/Mode-Global-Holdings-PLC-Mode-adopts-Bitcoin-as-tr/83499996

**Comment by nvk** [comment]
last report https://www.londonstockexchange.com/news-article/MODE/interim-results-for-the-period-ended-30-june-2020/14716173

**Comment by nvk** [comment]
Seems like only 6.7 BTC, no point in adding.

**Comment by shawnholt** [comment]
I believe that the list grows, ANY company that invests in bitcoin should be added.   Hopefully that will incentivize adoption.

**Comment by nvk** [comment]
Nope.
