### ISSUE TITLE
Issue: New Submission - HIVE Blockchain Technologies

### ISSUE THREAD

**Issue by btc1951** [nvk/bitcointreasuries.org#56]
- [ ] Name: HIVE Blockchain Technologies
- [ ] Exchange: (OTC: HVBTF)
- [ ] https://ca.finance.yahoo.com/quote/HIVE.V/
- [ ] Basis price: $0.36 USD
- [ ] Market Cap: $122.12 million USD
- [ ] Total BTC: 142 BTC (as of 1Q21 Financials for the Three Months Ended June 30, 2020) - Reference Note 10. in the Financial Statements as to Methodology Behind Calculation.
- [ ] Direct link to latest financial report - Attached
[HIVE Blockchain 1Q21 Financials.pdf](https://github.com/nvk/bitcointreasuries.org/files/5417358/HIVE.Blockchain.1Q21.Financials.pdf)

**Comment by nvk** [comment]
Already on the website as CVE:HIVE
