### ISSUE TITLE
Issue: New Submission - DMG Blockchain Solutions

### ISSUE THREAD

**Issue by btc1951** [nvk/bitcointreasuries.org#57]
- [ ] Name: DMG Blockchain Solutions
- [ ] Exchange: (OTC: DMGGF)
- [ ] https://ca.finance.yahoo.com/quote/DMGGF?p=DMGGF
- [ ] Basis price: $0.07 USD
- [ ] Market Cap: $6 million USD
- [ ] Total BTC: ~86 BTC (as of 3Q20 Financials for the Nine Months Ended June 30, 2020) - Reference Note 5. in the Financial Statements.
[DMG Blockchain 3Q20 Financials.pdf](https://github.com/nvk/bitcointreasuries.org/files/5417424/DMG.Blockchain.3Q20.Financials.pdf)

- [ ] Direct link to latest financial report

**Comment by nvk** [comment]
Is this the same company? https://www.google.com/search?q=CVE:+DMGI&stick=H4sIAAAAAAAAAONgecRowS3w8sc9YSn9SWtOXmPU5OIKzsgvd80rySypFJLmYoOyBKX4uXj10_UNDdNMDHKNLC2TeACgTjT2PQAAAA&tbm=fin#scso=_GWeQX_2RI6a4gge96q74BQ7:0

**Comment by btc1951** [comment]
Hi nvk, that is the same company.

**Comment by nvk** [comment]
It's already on the list then.
