### ISSUE TITLE
Cypherpunk Holdings Updated Numbers for September

### ISSUE THREAD

**Issue by ptbitcoiner** [nvk/bitcointreasuries.org#61]
- [ ] Name: Cypherpunk Holdings
- [ ] Exchange: symbol (HODL:TSX) 
- [ ] Total BTC: Holdings increased to 263.6 BTC at September update
- [ ] https://webfiles.thecse.com/CNSX_Form_7_September_2020.pdf?FlMOpY.f.D8nZ70v8E0tv.5NhxjQvr2O=

**Comment by nvk** [comment]
added
