### ISSUE TITLE
Add Mode Global Holdings PLC

### ISSUE THREAD

**Issue by nvk** [nvk/bitcointreasuries.org#62]
- 980,000 of BTC ann Oct 24 (13k?) https://www.forbes.com/sites/billybambrough/2020/10/24/exclusive-uk-listed-fintech-mode-now-holds-1-million-of-bitcoin
- Is this them, forbes doesn't show the symbol https://www.google.com/search?q=Mode+lse&tbm=fin#scso=_0xCYX4yPILHv_QbY-YLAAQ7:0

Little information on this.

**Comment by windsok** [comment]
https://modeplc.com/ (LON: MODE) appears to be the holding company, while https://modebanking.com/ is the consumer app they own.

Here is an article about putting their cash reserves into bitcoin: https://modebanking.com/2020/10/27/an-open-letter-from-mode/

**Comment by windsok** [comment]
Looks like they only went public on 5th October, this feels more like something they did to create PR. We probably need to wait until their first quarterly report to find out how much they actually have invested in bitcoin.

**Comment by practicalswift** [comment]
Clarification for readers of the OP: "980,000 of BTC" should be read as "980,000 USD of BTC" not "980,000 BTC" :)
