### ISSUE TITLE
Share the google sheet with this data so that we can use it in our calculations.

### ISSUE THREAD

**Issue by martijnw** [nvk/bitcointreasuries.org#63]
Already tweeted about this some time ago but got no reply. It would help make it easier to actually use the data in BTC calculations if the source sheet that's embedded into this page was shared as a read only google sheet.

No problem if you do not want to do this because google sheets allows scraping of web pages but would make it more robust. 

Anyway, that's my suggestion. Thank you for making this overview and hope it turns into the definitive guide/list of institutional investors in BTC.

**Comment by nvk** [comment]
For now will keep it simple.
