### ISSUE TITLE
Bitcoin Treasury holdings

### ISSUE THREAD

**Issue by mindinonline** [nvk/bitcointreasuries.org#64]
Going to guess the list is just scratching the surface. Banks such as Goldman Sachs may not be classifying it on their balance sheet. A lot of organizations. There are how many Bitcoin circulating right now. What about miners too. They are likely holding on to some. Governments? FOIA?
https://bitcointreasuries.org/

**Comment by nvk** [comment]
If you can find some interesting actors holding significant amounts, worth making a submission :)
