### ISSUE TITLE
Add hanetf BTCetc Bitcoin Exchange Traded Crypto

### ISSUE THREAD

**Issue by dessy888** [nvk/bitcointreasuries.org#65]
https://www.hanetf.com/product/8/fund/btcetc-bitcoin-exchange-traded-crypto-btce

BTCetc Bitcoin Exchange Traded Crypto (Ticker: BTCE) is an exchange traded cryptocurrency (ETC) that tracks the price of Bitcoin.

The ETC is 100% physically backed by Bitcoin and trades on Deutsche Börse´s XETRA, It is the world’s first centrally cleared Bitcoin ETC, providing investors with one of the safest and most liquid ways to gain exposure to Bitcoin. Each unit of BTCE gives the holder a claim on a predefined amount of Bitcoin.

**Comment by nvk** [comment]
please follow the template.
