### ISSUE TITLE
Update Grayscale Bitcoin balance

### ISSUE THREAD

**Issue by ChakTochi** [nvk/bitcointreasuries.org#66]
- [ ] Name: Grayscale Bitcoin Trust
- [ ] Exchange: OTCQX:GBTC
- [ ] Link https://grayscale.co/bitcoin-trust/ and https://www.otcmarkets.com/stock/GBTC/overview
- [ ] Basis price: $XXX USD
- [ ] Market Cap: $7,748,368,044 
- [ ] Total BTC: 481711 BTC
- [ ] Direct link to latest financial report https://grayscale.co/bitcoin-trust/

**Comment by nvk** [comment]
updated. thx!
