### ISSUE TITLE
Nova Aliança

### ISSUE THREAD

**Issue by deusvivo** [nvk/bitcointreasuries.org#67]
- [x] Name: Coin Citadel OTC
- [x] Exchange: symbol (NASDA:SQ) or wherever I can find it
- [x] Link to google finance or wherever I can find it
- [x] Basis price: $XXX USD
- [x] Market Cap: $XXX USD
- [x] Total BTC: XXX BTC
- [x] Direct link to latest financial report

**Comment by nvk** [comment]
No details.
