### ISSUE TITLE
Aesthetic Design

### ISSUE THREAD

**Issue by Psycarlo** [nvk/bitcointreasuries.org#7]
Working on a more aesthetic design for the website - prototype in AdobeXD.
I will show here soon.

_Probably won't work with Google Spreadsheet iframe_

**Comment by Psycarlo** [comment]
First Iteration (without table yet)

![](https://i.imgur.com/Xjl4ZuL.png)

&

![](https://i.imgur.com/iZ6jkjR.png)

**Comment by nvk** [comment]
Thanks, that's very kind. But it's not the look i'm going for :)
