### ISSUE TITLE
Feature request: Show percentage of treasuries invested in BTC

### ISSUE THREAD

**Issue by practicalswift** [nvk/bitcointreasuries.org#70]
First, thanks for a very nice resource @nvk!

It would be interesting if the site showed percent of treasuries invested in BTC.

In other words: `BTC treasuries / (BTC treasuries + non-BTC treasuries)`.

It could be argued that that is the better measure of a company's willingness to use BTC for treasuries purposes than the currently displayed "BTC %" (`BTC / market cap`).

The way I see it the `BTC / market cap` (the "BTC %" column) is more a measure of the market's belief (or rather non-belief) in the company's core business :)

**Comment by nvk** [comment]
I ran out of width on mobile.
