### ISSUE TITLE
3iQ The Bitcoin Fund - Update

### ISSUE THREAD

**Issue by CALoewen** [nvk/bitcointreasuries.org#72]
Name: 3iQ The Bitcoin Fund
Exchange: TSX:QBTC.U 
Link: [https://money.tmx.com/en/quote/QBTC.U](url)
IPO price: $10.00 USD
NAV at Inception: $9.2396 USD
Market Cap: $167,062,444.81 USD
Total BTC: 10,599.84 BTC
% BTC: 99%
Direct link to latest financial report: [https://3iq.ca/the-bitcoin-fund/](url) and [sedar.com](url)
Latest fund holdings available at: [https://docs.google.com/spreadsheets/d/1rnO1Q1ijb-qSdBAFeyXzX4fYfxJLfdyz308LXo776no/edit?usp=sharing](url)
Data as of November 11, 2020.

**Comment by nvk** [comment]
updated.

**Comment by CALoewen** [comment]
Name: 3iQ The Bitcoin Fund
Exchange: TSX:QBTC.U
Link: https://money.tmx.com/en/quote/QBTC.U
IPO price: $10.00 USD
NAV at Inception: $9.2396 USD
Market Cap: $320,783,100.51 USD
Total BTC: 16,484.55 BTC
% BTC: 100%
Direct link to latest financial report: https://3iq.ca/the-bitcoin-fund/ and sedar.com
Latest fund holdings available at: https://docs.google.com/spreadsheets/d/1rnO1Q1ijb-qSdBAFeyXzX4fYfxJLfdyz308LXo776no/edit?usp=sharing
Data as of November 30, 2020.
