### ISSUE TITLE
feature request: link to actual bitcoin wallets, where possible

### ISSUE THREAD

**Issue by xalspaero** [nvk/bitcointreasuries.org#74]
Great website.  You know what would make it even better?  In the BTC balance column, provide an actual link to the specific wallet address in question!

Of course, we won't have that info for all of them, and/or some could be broken into multiple wallets.  Still, for the ones with a known address or set of addresses, it would be great to have a direct link to the wallet on a block explorer.  What's not to love?

Either have the BTC balance itself be a link, or even add a new column for it.

**Comment by nvk** [comment]
Would be great, but unfortunately none of them have that information.
