### ISSUE TITLE
Currency Confusion

### ISSUE THREAD

**Issue by Bartholomeusforeskin** [nvk/bitcointreasuries.org#75]
I've noticed that Cypherpunk Holdings Inc. and Hut 8 Mining Corp have their market cap written in US dollars - but in reality it is their market cap in Canadian dollars, thus making them seem worth more than they actually are and deceive the % BTC ratio. Perhaps this is a problem on other Canadian noted stocks, or I might be completely out of the woods. I'm making this post to find out.
 
//Bart

**Comment by nvk** [comment]
Its all USD.
