### ISSUE TITLE
Cypherpunk Holding [Update]

### ISSUE THREAD

**Issue by juleznakamoto** [nvk/bitcointreasuries.org#76]
Already on your list, now owning 276.479 BTC

proof:
https://github.com/nvk/bitcointreasuries.org/issues/new
https://menafn.com/1101191514/Cypherpunk-Holdings-Inc-Announces-Updated-Bitcoin-Holdings

**Comment by nvk** [comment]
updated https://twitter.com/nvk/status/1332116225804079105?s=20
