### ISSUE TITLE
21Shares update

### ISSUE THREAD

**Issue by EliezerNdinga** [nvk/bitcointreasuries.org#81]
Hi there, 

21Shares now holds a total of 4,867.18357858 BTC across our ETPs. Here's the breakdown below, thanks in advance for updating! Best, Eli. 

ABBA	 291.76730819
ABTC	 3,378.41944580
HODL	 849.83359606
KEYS	 98.36003336
MOON	 248.80319517
	
Total	 4,867.18357858

**Comment by nvk** [comment]
thx, updated https://twitter.com/nvk/status/1335964207326621697?s=20
