### ISSUE TITLE
VanEck Vectors Bitcoin ETN

### ISSUE THREAD

**Issue by MarkusMeinert** [nvk/bitcointreasuries.org#85]
- [ ] Name: VanEck Vectors Bitcoin ETN
- [ ] Exchange: XETRA:VBTC     DE000A28M8D0
- [ ] https://www.vaneck.com/de/en/etf/digital-assets/vbtc/fact-sheet/
- [ ] Basis price: $XXX USD
- [ ] Market Cap: $2 Million USD (today)
- [ ] Total BTC: 100 BTC (approximately)
- [ ] Direct link to latest financial report

**Comment by nvk** [comment]
222 BTC.

Waiting for min 1K for ETN/ETF additions.

**Comment by Cryptobatman420** [comment]
Why does it matter if they only bought 222 btc? I think its still an achievement even if a publicly traded company bought 1 btc....

**Comment by nvk** [comment]
It's an ETN, I wasn't going to list AUM type companies. But GBTC is too large to ignore. So I created my arbitrary minimum threshold for this type.

**Comment by Cryptobatman420** [comment]
ok understood.
