### ISSUE TITLE
Bitwise 10 Crypto Index Fund

### ISSUE THREAD

**Issue by tboydsto** [nvk/bitcointreasuries.org#86]
- [x] Name: Bitwise 10 Crypto Index Fund
- [x] Exchange: BITW (OTCQX)
- [x] https://finance.yahoo.com/quote/BITW/
- [x] Basis price:  $45,370,629 USD
- [x] Market Cap: $60,006,852 USD
- [x] Total BTC:  4,233.8080 BTC
- [x] https://sec.report/otc/financial-report/263210/Third-Quarter-2020.pdf

**Comment by nvk** [comment]
Do you have a good finance link? (long story short its how the system works now)

**Comment by tboydsto** [comment]
No.  Google Finance appears to not list it (assuming that is what you
meant).  BITW is listed on all other finance sites I’ve queried.  Not sure
why Google does not have it.

**Comment by tboydsto** [comment]
Other sites if they work:

https://www.bloomberg.com/quote/BITW:US
https://research.tdameritrade.com/grid/public/research/stocks/summary?fromPage=overview&display=&fromSearch=true&symbol=BITW

**Comment by nvk** [comment]
No luck so far, the current setup is based on Google Spreadsheets, and they dropped support for script. There are some hacks but they seem to break all the time. I will leave this issue open. Maybe the Bitwise guys can ask to be listed on Google Finance.

**Comment by tboydsto** [comment]
I sent feedback to Google Finance

**Comment by nvk** [comment]
live https://twitter.com/BTCtreasuries/status/1339233872677105671?s=20

**Comment by bpdavenport** [comment]
Ignore Yahoo/Google finance. Take it from the horse's mouth: https://www.bitwiseinvestments.com/funds/Bitwise-10

**Comment by nvk** [comment]
Went with 6,590BTC (spot atm)
