### ISSUE TITLE
DigitalX - ASX: DCC - Australian company 

### ISSUE THREAD

**Issue by 24hourwealthcoach** [nvk/bitcointreasuries.org#88]
- [x] Name: DigitalX
- [x] Exchange: ASX: DCC
- [x] https://www.coindesk.com/asx-listed-digitalx-seeds-new-fund-with-half-its-bitcoin-holdings
- [ ] Basis price: $XXX USD
- [ ] Market Cap: $XXX USD
- [x] Total BTC: 431 BTC
- [ ] Direct link to latest financial report

**Comment by nvk** [comment]
Would be great to get the missing items

**Comment by tristanhcole** [comment]
They purchased Bitcoin ages ago, but looks like they've sold a lot since then. https://www.coindesk.com/digitalbtc-buys-10-1m-in-bitcoin-in-q2-2015

I sent an email to their investor relations. Thanks @nvk for the great website :)
