### ISSUE TITLE
MSTR 625 purchase

### ISSUE THREAD

**Issue by nvk** [nvk/bitcointreasuries.org#89]
Waiting on details.

**Comment by HansHauge** [comment]
I think it was $650 the last we heard.

https://www.microstrategy.com/en/company/company-videos/microstrategy-completes-650-million-offering-of-convertible-senior-notes

**Comment by nvk** [comment]
Yes, need filing details

**Comment by ViktorBohu** [comment]
**70,470 BTC** total

https://www.microstrategy.com/en/company/company-videos/microstrategy-announces-over-1b-in-total-bitcoin-purchases-in-2020

**Comment by ViktorBohu** [comment]
Can be closed #100

[#100](https://github.com/nvk/bitcointreasuries.org/issues/100)
