### ISSUE TITLE
Columns not summing?

### ISSUE THREAD

**Issue by HansHauge** [nvk/bitcointreasuries.org#91]
Hey @nvk I'm not sure if you monitor the closed issues, but I think there's an issue with the column summing on that last addition. See [here](https://github.com/nvk/bitcointreasuries.org/issues/90#issuecomment-746582911).

Cheers.

**Comment by nvk** [comment]
was fixed

**Comment by nvk** [comment]
try to keep it to less new issues, you rbought that up on the other issue already.
