### ISSUE TITLE
Ruffer

### ISSUE THREAD

**Issue by LukeParker** [nvk/bitcointreasuries.org#93]
- RUFFER INVESTMENT COMPANY LIMITED
- LSE:RICA
- https://www.google.com/search?q=LSE%3ARICA
- ?
- ?
- 2.5% of their portfolio on Dec 15, Today 2.7%
- https://www.londonstockexchange.com/news-article/RICA/performance-update-manager-comment/14794095

Kevin Helms did the math here: https://news.bitcoin.com/asset-manager-ruffer-750-million-bitcoin-investment-hedge-fiat-currency-devaluation/

It appears they have 35,877 BTC.

**Comment by nvk** [comment]
#90 already has an issue.
