### ISSUE TITLE
New: One River Digital Asset Management 

### ISSUE THREAD

**Issue by obsidience** [nvk/bitcointreasuries.org#94]
- [x] Name: One River Digital Asset Management 
- [ ] Exchange: Private https://www.oneriveram.com/digital-assets-strategies
- [x] https://cms.zerohedge.com/markets/giant-bitcoin-whale-emerges-transformational-1-billion-stake-backing-legendary-traders
- [ ] Basis price: < $16k
- [x] Market Cap: $1.6Bn USD
- [ ] Total BTC: Unknown, mixture of $1Bn BTC and ETH
- [ ] Unknown

**Comment by nvk** [comment]
Do we have a more official report/announcement and purchase details?

**Comment by obsidience** [comment]
I dug around but could not find one unfortunately.

**Comment by obsidience** [comment]
One River appears to be the purchaser or managing the $745mm BTC from Ruffer.  Unclear if One River has it's own stake.  

https://www.crypto-news-flash.com/one-river-digital-will-hold-1-billion-in-bitcoin-and-ethereum-by-2021/

Please feel free to close unless you want to keep tracking them.

**Comment by nvk** [comment]
We can revisit later if they announce more details.

**Comment by jnmclarty** [comment]
This article speculates that ~50,000 were withdrawn from coinbase.  Assuming average daily withdrawals is around 5K BTC, that leaves approx 50K BTC unaccounted for.  Maybe some chain-analysis on that day can determine the exact number.

More: https://decrypt.co/53200/one-river-makes-one-of-the-largest-cryptocurrency-trades-in-history

Even if half of that ~50K withdrawal wasn't them, there is still a good amount at likely _some institution_.
