### ISSUE TITLE
hanetf BTCetc Bitcoin Exchange Traded Crypto

### ISSUE THREAD

**Issue by nazjunaid** [nvk/bitcointreasuries.org#95]
TICKER: XETR:BTCE

https://www.hanetf.com/product/8/fund/btcetc-bitcoin-exchange-traded-crypto-btce

https://uk.tradingview.com/symbols/XETR-BTCE/

Total Holdings (Number of Bitcoin): 10316.070
Value of Bitcoin Holding** (USD): $200,194,187.68

**Comment by nazjunaid** [comment]
Not sure if this is a dupe of ETC Group Bitcoin ETP

**Comment by nvk** [comment]
Could you resubmit with the template?
