### ISSUE TITLE
Grayscale Digital Large Cap Fund

### ISSUE THREAD

**Issue by tjaderxyz** [nvk/bitcointreasuries.org#96]
- [ ] Name: Grayscale Digital Large Cap Fund
- [ ] Exchange: https://grayscale.co/digital-large-cap/
- [ ] https://www.otcmarkets.com/stock/GDLC/overview
- [ ] Basis price: $22.65 USD
- [ ] Market Cap: $178.9M USD
- [ ] Total BTC: 7036 BTC
- [ ] https://grayscale.co/wp-content/uploads/2020/11/DLC-Q1-2021-Report-and-FS_As-Filed.pdf

**Comment by nvk** [comment]
Grayscale is already listed. This side product seems to be a mix bag of shitcoins, also tiny beside the other 546,544 BTC

**Comment by tjaderxyz** [comment]
Perhaps it should be added to the GBTC listing then, like the 21Shares
listing.

It is "tiny" but still bigger than all but three of the public company
listings.


Em qua, 16 de dez de 2020 22:24, nvk <notifications@github.com> escreveu:

**Comment by nvk** [comment]
gets confusing... but noted.

**Comment by nvk** [comment]
Basis price is not clear. Leaving it blank for now. 

Added https://twitter.com/BTCtreasuries/status/1339596948467187715?s=20
