### ISSUE TITLE
WisdomTree Bitcoin

### ISSUE THREAD

**Issue by alelorca** [nvk/bitcointreasuries.org#97]
- [ ] Name: WisdomTree Bitcoin
- [ ] Exchange: symbol (BTCW:SW), ISIN: GB00BJYDH287
- [ ] https://www.wisdomtree.eu/en-gb/products/ucits-etfs-unleveraged-etps/cryptocurrency/wisdomtree-bitcoin
- [ ] Six exchange: https://www.six-group.com/en/products-services/the-swiss-stock-exchange/market-data/etp/etp-explorer/etp-detail.html?valorId=GB00BJYDH287USD4
- [ ] Yahoo Finance: https://finance.yahoo.com/quote/BTCW.SW/ (It should be trading in USD, in EUR the ticket is WBTC)
- [ ] Basis price: ???
- [ ] Market Cap:  $117 M
- [ ] Total BTC:  5699.8385358 BTC (2020-12-16)

**Comment by alelorca** [comment]
It is not available for world-wide investors, only for a limited european countries.

**Comment by nvk** [comment]
live https://twitter.com/BTCtreasuries/status/1339596948467187715?s=20
